// 0024 company workspaces
export default async ({ db, ok, as, svc, A, B, C, ADMIN }) => {
  const E = '00000000-0000-4000-8000-0000000000ee' // second employee
  await svc(`insert into auth.users values ('${E}')`)
  console.log('company continuity')
  let r = await as(A, `select public.create_organization('Acme Manufacturing', 'acme.com') as id`)
  const org = r.rows[0].id
  ok(!!org, 'member creates an organization and becomes admin')
  r = await as(C, `select id from public.organizations`)
  ok(r.rows.length === 0, 'outsiders cannot see the organization')
  r = await as(C, `select public.create_org_invite($1) as code`, [org])
  ok(!!r.error, 'non-admin cannot create invites')
  r = await as(A, `select public.create_org_invite($1, 5) as code`, [org])
  const code = r.rows[0].code
  r = await as(A, `select public.join_organization($1) as id`, [code])
  r = await as(A, `select role, status from public.org_members where user_id = $1`, [A])
  ok(r.rows[0].role === 'admin', 'sole admin entering their own code stays admin')
  r = await as(A, `select uses from public.org_invites where code = $1`, [code])
  ok(r.rows[0].uses === 0, 'an active member re-entering a code does not use it up')
  r = await as(B, `select public.join_organization($1) as id`, [code.toLowerCase()])
  ok(r.rows?.[0]?.id === org, 'member joins with an invite code (case-insensitive)')
  r = await as(E, `select public.join_organization($1) as id`, [code])
  r = await as(C, `select public.join_organization('NOTAREALCODE') as id`)
  ok(!!r.error, 'invalid codes are refused')
  r = await as(B, `insert into public.org_members (org_id, user_id, role) values ($1, $2, 'admin')`, [org, B])
  ok(!!r.error, 'cannot self-promote by writing the roster directly')
  r = await as(B, `select * from public.org_invites`)
  ok(r.rows.length === 0, 'non-admins cannot read invite codes')

  // B shares two relationships; E shares one that overlaps with B's.
  r = await as(B, `insert into public.org_shared_relationships (org_id, contact_name, contact_company, strength, context) values ($1, 'Dana Ortiz', 'Northwind', 'trusted', 'Their CFO; owns the renewal') returning id`, [org])
  ok(!r.error, 'active member shares a relationship: ' + (r.error ?? 'ok'))
  const share = r.rows[0].id
  await as(B, `insert into public.org_shared_relationships (org_id, contact_name, contact_company) values ($1, 'Sam Lee', 'Contoso')`, [org])
  await as(E, `insert into public.org_shared_relationships (org_id, contact_name, contact_company) values ($1, 'dana ortiz', 'NORTHWIND')`, [org])
  // B shares Sam twice: still one holder.
  await as(B, `insert into public.org_shared_relationships (org_id, contact_name, contact_company) values ($1, 'SAM LEE', 'contoso')`, [org])
  r = await as(A, `select * from public.org_relationship_coverage($1)`, [org])
  ok(r.rows.find(x => x.contact_name.toLowerCase() === 'sam lee')?.coverage === 'single_owner', 'one person sharing a contact twice is still a single holder')
  r = await as(C, `insert into public.org_shared_relationships (org_id, contact_name) values ($1, 'X')`, [org])
  ok(!!r.error, 'non-members cannot share into the workspace')
  r = await as(E, `insert into public.org_shared_relationships (org_id, owner_id, contact_name) values ($1, $2, 'Forged')`, [org, B])
  ok(!!r.error, 'cannot share in someone else\'s name')
  r = await as(A, `select contact_name from public.org_shared_relationships order by contact_name`)
  ok(r.rows.length === 4, 'the active team reads shared relationships')
  r = await as(C, `select id from public.org_shared_relationships`)
  ok(r.rows.length === 0, 'outsiders read nothing')
  r = await as(E, `delete from public.org_shared_relationships where id = $1 returning id`, [share])
  ok(r.rows?.length === 0, 'cannot withdraw a colleague\'s share')

  // Handover drafted, then approved; admins see it only once approved.
  r = await as(B, `insert into public.org_handovers (org_id, note, open_loops) values ($1, 'Dana prefers email; renewal due in March', 'Send Sam the pricing deck') returning id`, [org])
  ok(!r.error, 'leaver drafts a handover: ' + (r.error ?? 'ok'))
  r = await as(A, `select id from public.org_handovers`)
  ok(r.rows.length === 0, 'admins cannot read a draft handover')
  r = await as(B, `update public.org_handovers set approved = true where org_id = $1 returning approved_at`, [org])
  ok(r.rows?.[0]?.approved_at, 'leaver approves the handover')
  r = await as(B, `update public.org_handovers set note = 'rewritten' where org_id = $1 returning note`, [org])
  ok(r.rows?.[0]?.note.startsWith('Dana prefers'), 'an approved handover is final')
  r = await as(A, `select note from public.org_handovers`)
  ok(r.rows.length === 1, 'admins read the approved handover')
  r = await as(E, `select note from public.org_handovers`)
  ok(r.rows.length === 0, 'non-admin colleagues do not read handovers')

  // Departure: B leaves. Shares stay with the company; B loses access and cannot withdraw.
  r = await as(E, `select public.record_org_departure($1, $2)`, [org, B])
  ok(!!r.error, 'a colleague cannot record someone else\'s departure')
  r = await as(A, `select public.record_org_departure($1, $2)`, [org, A])
  ok(!!r.error, 'the last admin cannot leave without a successor')
  r = await as(A, `select public.set_org_role($1, $2, 'member')`, [org, A])
  ok(!!r.error, 'the last admin cannot demote themselves')
  r = await as(B, `select public.record_org_departure($1, $2)`, [org, B])
  ok(!r.error, 'member leaves: ' + (r.error ?? 'ok'))
  r = await as(B, `select id from public.org_shared_relationships`)
  ok(r.rows.length === 0, 'departed member loses workspace access')
  r = await as(B, `delete from public.org_shared_relationships where id = $1 returning id`, [share])
  ok(r.rows?.length === 0, 'departed member cannot pull shared records back')
  r = await as(A, `select count(*)::int as n from public.org_shared_relationships`)
  ok(r.rows[0].n === 4, 'the company keeps everything that was shared')

  r = await as(A, `select * from public.org_relationship_coverage($1)`, [org])
  const cov = Object.fromEntries(r.rows.map(x => [x.contact_name.toLowerCase(), x]))
  ok(cov['sam lee']?.coverage === 'at_risk', 'contact held only by the leaver is flagged at risk')
  ok(cov['dana ortiz']?.coverage === 'single_owner' && cov['dana ortiz'].departed_owners === 1, 'overlapping contact merges and shows single owner left')
  r = await as(C, `select * from public.org_relationship_coverage($1)`, [org])
  ok(r.rows.length === 0, 'coverage is empty for non-members')
  r = await as(B, `select public.join_organization($1) as id`, [code])
  r = await as(B, `select role, status from public.org_members where user_id = $1`, [B])
  ok(r.rows[0].status === 'active' && r.rows[0].role === 'member', 'rejoining starts fresh as a member')
}
