// 0057 deal workspaces: private, participant-only, RPC-only writes, validated lifecycle
export default async ({ ok, as, svc, A, B, C, ADMIN }) => {
  const INTRO = '11111111-1111-4111-8111-111111111111' // accepted introduction between C and B (seed)
  const PENDING = '22222222-2222-4222-8222-222222222222' // C asked A, never accepted (seed)
  const [{ id: THREAD }] = await svc(`insert into public.dm_threads (member_a, member_b, created_by) values ('${A}', '${B}', '${A}') returning id`)
  const create = (uid, type, id, title = 'Logistics audit', extra = ``) =>
    as(uid, `select public.create_deal_workspace($1, $2, $3${extra}) r`, [type, id, title])

  // Creation: only from your own conversation or an accepted introduction.
  ok(!!(await create(C, 'dm_thread', THREAD)).error, 'an outsider cannot open a workspace from someone else\'s conversation')
  ok(!!(await create(A, 'intro_request', PENDING)).error && !!(await create(C, 'intro_request', PENDING)).error, 'an introduction nobody accepted cannot become a workspace')
  ok(!!(await create(A, 'intro_request', INTRO)).error, 'nor can a member outside that introduction')
  ok(!!(await create(A, 'dm_thread', THREAD, 'ab')).error, 'the title must be real')
  ok(!!(await as(A, `select public.create_deal_workspace('dm_thread', $1, 'Audit', '', '', 5000, null)`, [THREAD])).error, 'a budget needs a currency')
  ok(!!(await as(null, `select public.create_deal_workspace('dm_thread', $1, 'Audit')`, [THREAD])).error, 'visitors cannot')
  ok(!!(await as(A, `insert into public.deal_workspaces (source_type, source_id, title) values ('dm_thread', $1, 'Direct insert')`, [THREAD])).error, 'tables cannot be written directly')

  let r = await create(A, 'dm_thread', THREAD)
  ok(r.rows?.[0]?.r?.created === true, 'a member opens a workspace from a conversation')
  const WS = r.rows[0].r.id
  r = await create(A, 'dm_thread', THREAD)
  ok(r.rows?.[0]?.r?.created === false && r.rows[0].r.id === WS, 'submitting twice returns the same workspace')
  r = await create(B, 'dm_thread', THREAD)
  ok(r.rows?.[0]?.r?.id === WS && r.rows[0].r.created === false, 'the other person gets the existing workspace, not a second one')
  ok((await svc(`select count(*)::int n from public.deal_workspaces`))[0].n === 1, 'only one workspace exists for the source')
  ok((await svc(`select actor_id from public.deal_workspace_events where kind = 'created'`))[0].actor_id === A, 'the actor is the caller')
  ok((await svc(`select count(*)::int n from public.notifications where kind = 'workspace_invite' and user_id = '${B}'`))[0].n === 1, 'the other person is told once')

  // Reads: roster only.
  ok((await as(A, `select id from public.deal_workspaces`)).rows?.length === 1, 'the owner reads it')
  ok((await as(B, `select id, title from public.deal_workspaces`)).rows?.length === 1, 'an invited person can read it to decide')
  ok((await as(C, `select id from public.deal_workspaces`)).rows?.length === 0, 'outsiders see nothing')
  ok((await as(C, `select user_id from public.deal_workspace_members`)).rows?.length === 0, 'nor the roster')
  ok((await as(B, `select id from public.deal_workspace_events`)).rows?.length === 0, 'an invited person does not read the history yet')
  ok(!!(await as(null, `select id from public.deal_workspaces`)).error, 'visitors have no access')

  // Invited person cannot act until they accept; nobody else can accept for them.
  ok(!!(await as(B, `select public.add_workspace_step($1, 'Send NDA')`, [WS])).error, 'an invited person cannot add steps before accepting')
  ok(!!(await as(C, `select public.respond_workspace_invite($1, true)`, [WS])).error, 'an outsider cannot accept the invitation')
  ok(!!(await as(A, `select public.respond_workspace_invite($1, true)`, [WS])).error, 'the owner cannot accept on behalf of the invitee')
  ok(!!(await as(B, `update public.deal_workspace_members set status = 'active', role = 'owner'`)).error, 'the roster cannot be edited directly')
  ok(!(await as(B, `select public.respond_workspace_invite($1, true)`, [WS])).error, 'the invited person accepts')
  ok(!!(await as(B, `select public.respond_workspace_invite($1, true)`, [WS])).error, 'accepting twice is refused')
  ok((await as(B, `select id from public.deal_workspace_events`)).rows?.length >= 2, 'then the history is readable')

  // Role-specific writes.
  ok(!!(await as(B, `select public.update_workspace_details($1, 'Mine now', 'x', null, null, null)`, [WS])).error, 'a collaborator cannot change the terms')
  ok(!!(await as(C, `select public.update_workspace_details($1, 'Mine now', 'x', null, null, null)`, [WS])).error, 'nor an outsider')
  ok(!(await as(A, `select public.update_workspace_details($1, 'Logistics audit', 'Audit the dispatch process', 1200000, 'usd', '2026-12-01')`, [WS])).error, 'the owner sets scope, budget, currency and due date')
  ok(!!(await as(A, `select public.update_workspace_details($1, 'Logistics audit', 'x', 100, null, null)`, [WS])).error, 'a budget without currency is refused')
  ok(!!(await as(A, `select public.update_workspace_details($1, 'Logistics audit', 'x', -1, 'usd', null)`, [WS])).error, 'a negative budget is refused')
  ok(!(await as(B, `select public.set_workspace_next_action($1, 'Share dispatch export')`, [WS])).error, 'either participant sets the next action')
  ok(!!(await as(C, `select public.set_workspace_next_action($1, 'Hijack')`, [WS])).error, 'an outsider cannot')
  ok((await as(A, `select next_action from public.deal_workspaces`)).rows?.[0]?.next_action === 'Share dispatch export', 'and the owner sees it')
  r = await as(A, `select public.add_workspace_step($1, 'Send NDA') id`, [WS])
  const STEP = r.rows?.[0]?.id
  ok(!!STEP, 'a participant adds a shared step')
  ok(!!(await as(A, `select public.add_workspace_step($1, '   ')`, [WS])).error, 'blank steps are refused')
  ok(!(await as(B, `select public.set_workspace_step_done($1, true)`, [STEP])).error, 'the other participant ticks it off')
  ok((await as(A, `select done_by from public.deal_workspace_steps`)).rows?.[0]?.done_by === B, 'recorded against the real actor')
  ok(!!(await as(C, `select public.set_workspace_step_done($1, false)`, [STEP])).error, 'an outsider cannot change steps')
  ok(!!(await as(B, `update public.deal_workspace_steps set done_by = '${A}'`)).error, 'steps cannot be forged directly')

  // Lifecycle.
  ok(!!(await as(B, `select public.transition_workspace_status($1, 'proposal')`, [WS])).error, 'only the owner moves the stage')
  ok(!!(await as(A, `select public.transition_workspace_status($1, 'delivered')`, [WS])).error, 'stages cannot be skipped')
  ok(!!(await as(A, `select public.transition_workspace_status($1, 'agreed')`, [WS])).error, 'agreement cannot be declared by one person')
  ok(!!(await as(A, `update public.deal_workspaces set status = 'accepted'`)).error, 'status cannot be written directly')
  ok(!!(await as(A, `select public.transition_workspace_status($1, 'bogus')`, [WS])).error, 'unknown stages are refused')
  ok(!!(await as(A, `select public.confirm_workspace_milestone($1, 'agreed')`, [WS])).error, 'cannot confirm agreement before a proposal exists')
  ok(!(await as(A, `select public.transition_workspace_status($1, 'proposal')`, [WS])).error, 'the owner moves to proposal')
  ok((await as(A, `select public.confirm_workspace_milestone($1, 'agreed') s`, [WS])).rows?.[0]?.s === 'proposal', 'one confirmation does not make it agreed')
  ok((await as(A, `select status from public.deal_workspaces`)).rows?.[0]?.status === 'proposal', 'still a proposal')
  ok(!!(await as(C, `select public.confirm_workspace_milestone($1, 'agreed')`, [WS])).error, 'an outsider cannot confirm')
  ok(!(await as(A, `select public.update_workspace_details($1, 'Logistics audit', 'Audit dispatch and billing', 1200000, 'usd', '2026-12-01')`, [WS])).error, 'changing the scope...')
  ok((await svc(`select count(*)::int n from public.deal_workspace_confirmations`))[0].n === 0, '...voids earlier confirmations')
  await as(A, `select public.confirm_workspace_milestone($1, 'agreed')`, [WS])
  ok((await as(B, `select public.confirm_workspace_milestone($1, 'agreed') s`, [WS])).rows?.[0]?.s === 'agreed', 'agreed only once both participants confirmed')
  ok(!(await as(A, `select public.transition_workspace_status($1, 'in_progress')`, [WS])).error, 'then work starts')
  ok(!!(await as(B, `select public.transition_workspace_status($1, 'delivered')`, [WS])).error, 'the other person cannot declare delivery')
  ok(!(await as(A, `select public.transition_workspace_status($1, 'delivered')`, [WS])).error, 'the owner marks delivered')
  await as(A, `select public.confirm_workspace_milestone($1, 'accepted')`, [WS])
  ok((await as(A, `select status from public.deal_workspaces`)).rows?.[0]?.status === 'delivered', "the owner alone cannot accept their own delivery")
  ok((await as(B, `select public.confirm_workspace_milestone($1, 'accepted') s`, [WS])).rows?.[0]?.s === 'accepted', 'accepted once both confirm')
  ok(!!(await as(A, `select public.transition_workspace_status($1, 'cancelled')`, [WS])).error, 'an accepted workspace cannot be cancelled')
  ok(!(await as(A, `select public.transition_workspace_status($1, 'closed')`, [WS])).error, 'and is closed by the owner')
  ok(!!(await as(A, `select public.set_workspace_next_action($1, 'More')`, [WS])).error, 'a closed workspace takes no more changes')
  ok(!!(await as(A, `select public.transition_workspace_status($1, 'qualified')`, [WS])).error, 'a closed workspace cannot reopen')
  ok(!!(await as(A, `select public.add_workspace_step($1, 'Late step')`, [WS])).error, 'nor take new steps')
  ok(!!(await as(A, `update public.deal_workspace_events set detail = 'x'`)).error, 'history is not rewritable')
  ok(!!(await as(A, `delete from public.deal_workspace_events`)).error, 'or deletable')
  ok(await svc(`update public.deal_workspaces set status = 'qualified' where id = '${WS}'`).then(() => false, () => true), 'even the service role cannot walk the lifecycle backwards')

  // Introduction source, membership changes, private CRM link.
  r = await create(C, 'intro_request', INTRO, 'Fractional CFO engagement')
  const WS2 = r.rows?.[0]?.r?.id
  ok(!!WS2, 'an accepted introduction becomes a workspace')
  await as(C, `select public.add_workspace_step($1, 'Share rate card')`, [WS2])
  ok((await as(A, `select id from public.deal_workspaces where id = '${WS2}'`)).rows?.length === 0, 'unrelated members cannot read it')
  ok(!!(await as(C, `select public.invite_workspace_member($1, $2)`, [WS2, A])).error, 'the owner cannot add someone outside the introduction')
  ok(!!(await as(B, `select public.invite_workspace_member($1, $2)`, [WS2, A])).error, 'an invitee cannot invite anyone')
  ok(!(await as(B, `select public.respond_workspace_invite($1, false)`, [WS2])).error, 'the invitee can decline')
  ok((await as(C, `select count(*)::int n from public.deal_workspace_members where status = 'declined'`)).rows?.[0]?.n === 1, 'the owner sees the decline')
  ok(!(await as(C, `select public.invite_workspace_member($1, $2)`, [WS2, B])).error, 'the owner re-invites the other person')
  ok(!(await as(B, `select public.respond_workspace_invite($1, true)`, [WS2])).error, 'who accepts')
  ok(!!(await as(B, `select public.remove_workspace_member($1, $2)`, [WS2, C])).error, 'a collaborator cannot remove the owner')
  ok(!!(await as(A, `select public.remove_workspace_member($1, $2)`, [WS2, B])).error, 'an outsider cannot remove anyone')
  ok(!(await as(C, `select public.remove_workspace_member($1, $2)`, [WS2, B])).error, 'the owner removes a collaborator')
  ok((await as(B, `select id from public.deal_workspaces`)).rows?.filter(x => x.id === WS2).length === 0, 'who then loses access')
  ok((await as(B, `select id from public.deal_workspace_steps where workspace_id = '${WS2}'`)).rows?.length === 0, 'including its steps')

  await svc(`insert into public.crm_opportunities (id, owner_id) values ('33333333-3333-4333-8333-333333333333', '${C}')`)
  ok(!(await as(C, `select public.link_workspace_opportunity($1, '33333333-3333-4333-8333-333333333333')`, [WS2])).error, 'the owner links their own CRM opportunity')
  ok(!!(await as(C, `select public.link_workspace_opportunity($1, '44444444-4444-4444-8444-444444444444')`, [WS2])).error, 'but not one they do not own')
  ok((await as(A, `select crm_opportunity_id from public.deal_workspace_crm_links`)).rows?.length === 0, 'the link is private')
  ok(!!(await as(C, `insert into public.deal_workspace_crm_links (workspace_id, crm_opportunity_id) values ('${WS2}', '33333333-3333-4333-8333-333333333333')`)).error, 'links cannot be written directly')
  ok(!!(await as(C, `truncate public.deal_workspaces`)).error, 'members cannot truncate')
}
