// 0029 recorded live-only objects, 0030 lockdown of their access
export default async ({ ok, as, svc, A, B }) => {
  console.log('operator functions')
  for (const call of ['network_health()', `network_brief('${A}', 7)`, `run_verification_scan('${B}')`, 'nudge_incomplete_onboarding()', `member_profile_strength('${B}')`]) {
    ok(!!(await as(null, `select public.${call}`)).error, `anon cannot call ${call.split('(')[0]}`)
    ok(!!(await as(A, `select public.${call}`)).error, `a member cannot call ${call.split('(')[0]}`)
  }
  ok((await svc(`select public.network_health() is not null as ok`))[0].ok, 'the service role still can')

  console.log('match_reasoning')
  await svc(`update public.profiles set name = 'Ana', can_help_with = 'CFO search', looking_for = 'Board seats' where id = '${A}'`)
  await svc(`update public.profiles set name = 'Ben', can_help_with = 'Board seats', looking_for = 'CFO search', focus = 'Growth' where id = '${B}'`)
  ok(!!(await as(null, `select public.match_reasoning('${A}', '${B}')`)).error, 'anon cannot read match reasoning')
  let r = await as(A, `select public.match_reasoning('${B}', '${A}') as j`)
  ok(r.rows[0].j === null, "a member cannot read reasoning as someone else (it exposes both profiles)")
  r = await as(A, `select public.match_reasoning('${A}', '${B}') as j`)
  ok(r.rows[0].j?.score > 0, 'a member gets reasoning for themselves')

  console.log('member directory')
  r = await svc(`select count(*)::int n from public.members_base where id in ('${A}', '${B}') and not is_demo`)
  ok(r[0].n === 2, 'profile changes sync live member cards into members_base')
  await svc(`insert into public.members_base (id, name, initials, title, company, location, role, industry, is_demo) values ('demo-ava', 'Ava Demo', 'AD', 'CEO', 'Demo Co', 'Austin', 'Founder', 'SaaS', true)`)
  await svc(`update public.members set title = 'Chair' where id = '${B}'`)
  ok((await svc(`select title from public.members_base where id = '${B}'`))[0].title === 'Chair', 'the service role still writes through the view')
  r = await as(null, `insert into public.members (id, name, initials, title, company, location, role, industry, is_demo) values ('${B}', 'Hijacked', 'H', 'x', 'x', 'x', 'x', 'x', false)`)
  ok(!!r.error, 'anon cannot write the directory through the view')
  r = await as(A, `insert into public.members (id, name, initials, title, company, location, role, industry, is_demo) values ('${B}', 'Hijacked', 'H', 'x', 'x', 'x', 'x', 'x', false)`)
  ok(!!r.error, "a member cannot overwrite another member's card through the view")
  r = await as(A, `update public.members set name = 'Hijacked' where id = '${B}'`)
  ok(!!r.error, 'a member cannot edit the directory through the view')
  r = await as(A, `update public.members_base set name = 'Hijacked' where id = '${B}'`)
  ok(!!r.error, 'a member cannot edit members_base directly')
  ok((await svc(`select name from public.members_base where id = '${B}'`))[0].name === 'Ben', 'the card is unchanged')
  r = await as(A, `select id, why_them from public.members where id = '${B}'`)
  ok(r.rows?.[0]?.why_them?.startsWith('Ben can help with'), 'members still read live cards with personal reasoning')
  r = await as(null, `select id from public.members`)
  ok(r.rows?.length === 1 && r.rows[0].id === 'demo-ava', 'visitors see only demo cards')
  r = await as(A, `insert into public.intro_requests (user_id, member_id) values ($1, 'demo-ava') returning id`, [A])
  ok(!!r.error, 'introductions to demo fixtures are refused')

  console.log('events')
  await svc(`insert into public.memories (user_id, member_id, text, source) values ('${A}', '${B}', 'Private: Ben is weak on follow-up', 'note')`)
  ok((await svc(`select count(*)::int n from public.events where type = 'memory.recorded' and user_id = '${A}' and person_id = '${B}'`))[0].n === 1, 'memories emit an event')
  r = await as(B, `select payload from public.events where user_id = '${A}'`)
  ok(r.rows.length === 0, "the person a private note is about cannot read it from events")
  r = await as(A, `select count(*)::int n from public.events where user_id = $1`, [A])
  ok(r.rows[0].n >= 1, 'members read their own events')
  ok(!!(await as(null, `select id from public.events`)).error, 'anon cannot read events')
  r = await as(A, `insert into public.events (user_id, type) values ($1, 'member.onboarded')`, [A])
  ok(!!r.error, 'members cannot forge events')

  console.log('recorded behaviour')
  await svc(`insert into public.memories (user_id, text, source) values ('${A}', 'Goal: raise a seed round', 'profile')`)
  await svc(`insert into public.memories (user_id, text, source) values ('${A}', 'Goal: hire a CFO', 'profile')`)
  r = await svc(`select text from public.memories where user_id = '${A}' and fact_key = 'goal'`)
  ok(r.length === 1 && r[0].text === 'Goal: hire a CFO', 'a restated fact replaces the earlier one')
  r = await as(A, `insert into public.asks (id, author_id, ask) values ('ask-live', $1, 'Need a CFO') returning member_id, posted`, [A])
  ok(r.rows?.[0]?.member_id === A && r.rows[0].posted === 'Just now', 'asks get their member id and label stamped')

  await svc(`delete from public.memories where user_id = '${A}'`)
  await svc(`delete from public.asks where id = 'ask-live'`)
}
