// 0031 video meetings: roster, consent-gated transcript, private notes, private call channel
export default async ({ ok, as, svc, A, B, C }) => {
  const D = '00000000-0000-4000-8000-0000000000dd'
  await svc(`insert into auth.users (id) values ('${D}') on conflict do nothing`)
  await svc(`insert into public.profiles (id, name) values ('${D}', 'Dee') on conflict (id) do nothing`)
  await svc(`update public.profiles set name = 'Ana' where id = '${A}'`)

  console.log('create')
  ok(!!(await as(null, `select public.create_meeting('Pipeline review', array['${B}']::uuid[])`)).error, 'visitors cannot create meetings')
  const five = `array['${B}','${C}','${D}','00000000-0000-4000-8000-0000000000ad']::uuid[]`
  ok(!!(await as(A, `select public.create_meeting('Too many', ${five})`)).error, 'a meeting holds at most four people')
  let r = await as(A, `select public.create_meeting('  Pipeline review  ', array['${B}', '${B}', '${A}', '00000000-0000-4000-8000-00000000ffff']::uuid[]) as id`)
  const m = r.rows[0].id
  r = await svc(`select user_id, role from public.meeting_participants where meeting_id = '${m}' order by role desc`)
  ok(r.length === 2 && r[0].user_id === A && r[0].role === 'host' && r[1].user_id === B, 'host plus real, de-duplicated invitees; self and unknown ids dropped')
  ok((await svc(`select title from public.meetings where id = '${m}'`))[0].title === 'Pipeline review', 'title is trimmed')
  r = await svc(`select text, link from public.notifications where user_id = '${B}' and kind = 'meeting_invite'`)
  ok(r.length === 1 && r[0].text.startsWith('Ana invited you') && r[0].link === '/app/meetings', 'invitees are notified')

  console.log('visibility')
  ok((await as(B, `select id from public.meetings where id = $1`, [m])).rows.length === 1, 'invitees see the meeting')
  ok((await as(C, `select id from public.meetings where id = $1`, [m])).rows.length === 0, 'outsiders do not')
  ok((await as(C, `select user_id from public.meeting_participants where meeting_id = $1`, [m])).rows.length === 0, 'outsiders cannot read the roster')
  ok(!!(await as(A, `insert into public.meetings (host_id, title) values ($1, 'x')`, [A])).error, 'meetings are created only through create_meeting')
  ok(!!(await as(C, `insert into public.meeting_participants (meeting_id, user_id) values ($1, $2)`, [m, C])).error, 'nobody can add themselves to a meeting')

  console.log('consent and transcript')
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'Hello') returning id`, [m])
  ok(!!r.error, 'no transcript lines before the speaker turns notes on')
  ok(!!(await as(C, `select public.set_meeting_notes_consent($1, true)`, [m])).error, 'outsiders cannot change consent')
  await as(B, `select public.set_meeting_notes_consent($1, true)`, [m])
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'We should hire a CFO') returning speaker_id`, [m])
  ok(r.rows?.[0]?.speaker_id === B, 'a consenting speaker adds lines as themselves')
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, speaker_id, text) values ($1, $2, 'Forged') returning id`, [m, A])
  ok(!!r.error, 'lines cannot be written as someone else')
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, text, spoken_at) values ($1, 'Backdated', now() - interval '1 day') returning id`, [m])
  ok(!!r.error, 'lines cannot be backdated')
  r = await as(A, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'Host talking') returning id`, [m])
  ok(!!r.error, "the host's consent is separate: no lines until they opt in too")
  ok((await as(A, `select text from public.meeting_transcript_lines where meeting_id = $1`, [m])).rows.length === 1, 'participants read the transcript')
  ok((await as(C, `select text from public.meeting_transcript_lines where meeting_id = $1`, [m])).rows.length === 0, 'outsiders cannot')
  await as(B, `select public.set_meeting_notes_consent($1, false)`, [m])
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'After opting out') returning id`, [m])
  ok(!!r.error, 'turning notes off stops transcription at once')
  r = await as(A, `delete from public.meeting_transcript_lines where meeting_id = $1 returning id`, [m])
  ok(r.rows.length === 0, "nobody can delete someone else's words")
  await as(B, `select public.set_meeting_notes_consent($1, true)`, [m])
  await as(B, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'Strike this') `, [m])
  r = await as(B, `delete from public.meeting_transcript_lines where meeting_id = $1 and text = 'Strike this' returning id`, [m])
  ok(r.rows.length === 1, 'speakers can delete their own lines')

  console.log('joining and ending')
  await as(B, `select public.mark_meeting_joined($1)`, [m])
  r = await svc(`select (select joined_at from public.meeting_participants where meeting_id = '${m}' and user_id = '${B}') is not null as j, started_at is not null as s from public.meetings where id = '${m}'`)
  ok(r[0].j && r[0].s, 'joining stamps the attendee and starts the meeting')
  ok(!!(await as(B, `select public.end_meeting($1)`, [m])).error, 'only the host ends the meeting')
  await as(A, `select public.end_meeting($1)`, [m])
  ok((await svc(`select count(*)::int n from public.meeting_participants where meeting_id = '${m}' and notes_consent`))[0].n === 0, 'ending switches note taking off for everyone')
  r = await as(B, `insert into public.meeting_transcript_lines (meeting_id, text) values ($1, 'Too late') returning id`, [m])
  ok(!!r.error, 'no lines after the meeting ends')
  ok(!!(await as(B, `select public.set_meeting_notes_consent($1, true)`, [m])).error, 'consent cannot be reopened after the end')

  console.log('notes')
  r = await as(B, `insert into public.meeting_notes (meeting_id, summary, action_items) values ($1, 'Agreed to hire a CFO', '[{"task":"Draft the role"}]') returning owner_id`, [m])
  ok(r.rows?.[0]?.owner_id === B, 'attendees save notes to their own account')
  ok(!!(await as(C, `insert into public.meeting_notes (meeting_id, summary) values ($1, 'x')`, [m])).error, 'outsiders cannot attach notes to the meeting')
  ok((await as(A, `select id from public.meeting_notes where meeting_id = $1`, [m])).rows.length === 0, "the host cannot read a guest's notes")
  ok(!!(await as(B, `update public.meeting_notes set owner_id = $2 where meeting_id = $1`, [m, A])).error, 'notes cannot be handed to someone else')
  r = await as(B, `update public.meeting_notes set private_note = 'Follow up Friday' where meeting_id = $1 returning private_note`, [m])
  ok(r.rows?.[0]?.private_note === 'Follow up Friday', 'owners edit their notes')
  ok(!!(await as(B, `insert into public.meeting_notes (meeting_id, summary, decisions) values ($1, 'dup', '{}')`, [m])).error, 'one notes record per person per meeting, decisions must be a list')

  console.log('private call channel')
  const topic = `meeting:${m}`
  await svc(`select set_config('realtime.topic', '${topic}', false)`)
  r = await as(B, `insert into realtime.messages (topic, extension, payload) values ($1, 'broadcast', '{}') returning id`, [topic])
  ok(!r.error, 'participants can signal on the meeting channel')
  ok((await as(B, `select id from realtime.messages`)).rows.length >= 1, 'participants receive on it')
  r = await as(C, `insert into realtime.messages (topic, extension, payload) values ($1, 'broadcast', '{}') returning id`, [topic])
  ok(!!r.error, 'outsiders cannot send on it')
  ok((await as(C, `select id from realtime.messages`)).rows.length === 0, 'outsiders cannot receive from it')
  await svc(`select set_config('realtime.topic', 'meeting:not-a-uuid', false)`)
  ok(!!(await as(B, `insert into realtime.messages (topic, extension, payload) values ('meeting:not-a-uuid', 'broadcast', '{}')`)).error, 'malformed meeting channels are refused')
  await svc(`select set_config('realtime.topic', '', false)`)
}
