// 0022 introduction outcomes, consent guard, check-ins, proof metrics
export default async ({ db, ok, as, svc, A, B, C, ADMIN }) => {
  console.log('backfill')
  let r = await svc(`select id, accepted_at, target_user_id from public.intro_requests order by id`)
  ok(r[0].accepted_at !== null, 'existing accepted intro gets accepted_at backfilled')
  ok(r[1].target_user_id === A, 'MCP-style request without target gets target_user_id backfilled from member_id')

  console.log('consent guard')
  r = await as(A, `insert into public.intro_requests (user_id, member_id, member_opt_in, status) values ($1, $2, true, 'introduced') returning id, member_opt_in, target_user_id, accepted_at`, [A, B])
  const intro = r.rows[0].id
  ok(r.rows[0].member_opt_in === false, 'requester cannot self-accept on insert')
  ok(r.rows[0].target_user_id === B, 'target derived from member_id on insert')
  ok(r.rows[0].accepted_at === null, 'no accepted_at before target opts in')
  r = await as(A, `insert into public.intro_requests (user_id, member_id, member_opt_in, status) values ($1, $2, true, 'introduced')
    on conflict (user_id, member_id) do update set member_opt_in = excluded.member_opt_in, status = excluded.status returning member_opt_in`, [A, B])
  ok(r.rows[0].member_opt_in === false, 'requester cannot self-accept through saveIntro-style upsert')
  r = await as(A, `update public.intro_requests set member_opt_in = true, accepted_at = now() where id = $1 returning member_opt_in, accepted_at`, [intro])
  ok(r.rows[0].member_opt_in === false && r.rows[0].accepted_at === null, 'requester cannot self-accept or forge accepted_at via update')
  r = await as(C, `update public.intro_requests set member_opt_in = true where id = $1 returning id`, [intro])
  ok(r.rows.length === 0, 'outsider cannot touch the request')
  r = await as(B, `update public.intro_requests set reason = 'rewritten', user_id = $2, requester_opt_in = false where id = $1 returning reason, user_id, requester_opt_in`, [intro, C])
  ok(r.rows[0].reason === '' && r.rows[0].user_id === A && r.rows[0].requester_opt_in === true, 'target cannot rewrite reason, requester or requester opt-in')

  r = await as(A, `insert into public.intro_outcomes (intro_request_id, stage) values ($1, 'met') returning id`, [intro])
  ok(!!r.error, 'outcome cannot be recorded before both sides opt in')

  r = await as(B, `update public.intro_requests set member_opt_in = true, status = 'accepted' where id = $1 returning member_opt_in, accepted_at`, [intro])
  ok(r.rows[0].member_opt_in === true && r.rows[0].accepted_at !== null, 'target accepts; accepted_at stamped by server')
  const stamped = r.rows[0].accepted_at
  r = await as(B, `update public.intro_requests set member_opt_in = false where id = $1 returning accepted_at`, [intro])
  r = await as(B, `update public.intro_requests set member_opt_in = true where id = $1 returning accepted_at`, [intro])
  ok(String(r.rows[0].accepted_at) === String(stamped), 'accepted_at is set once and never moves')

  console.log('outcomes RLS')
  r = await as(A, `insert into public.intro_outcomes (intro_request_id, stage) values ($1, 'met') returning id`, [intro])
  ok(!r.error, 'requester records met: ' + (r.error ?? 'ok'))
  r = await as(B, `insert into public.intro_outcomes (intro_request_id, stage, outcome_category, value_band, private_note, shareable) values ($1, 'outcome', 'customer', '100k_1m', 'secret', true) returning id`, [intro])
  ok(!r.error, 'target records shareable outcome: ' + (r.error ?? 'ok'))
  r = await as(C, `insert into public.intro_outcomes (intro_request_id, stage) values ($1, 'met') returning id`, [intro])
  ok(!!r.error, 'outsider cannot record an outcome')
  r = await as(A, `insert into public.intro_outcomes (intro_request_id, author_id, stage) values ($1, $2, 'met') returning id`, [intro, B])
  ok(!!r.error, 'cannot record an outcome as someone else')
  r = await as(A, `insert into public.intro_outcomes (intro_request_id, stage) values ($1, 'outcome') returning id`, [intro])
  ok(!!r.error, 'outcome stage requires a category')
  r = await as(A, `insert into public.intro_outcomes (intro_request_id, stage, value_band) values ($1, 'met', 'over_1m') returning id`, [intro])
  ok(!!r.error, 'value band only on outcome stage')
  r = await as(A, `select id, stage, author_id from public.intro_outcomes where intro_request_id = $1`, [intro])
  ok(r.rows.length === 2, 'requester sees own + shared outcome (' + r.rows.length + ')')
  r = await as(A, `select private_note from public.intro_outcomes`)
  ok(!!r.error, 'private_note column not readable directly')
  r = await as(B, `select * from public.my_intro_outcome_notes()`)
  ok(r.rows.length === 1 && r.rows[0].private_note === 'secret', 'author reads own note via RPC')
  r = await as(A, `select * from public.my_intro_outcome_notes()`)
  ok(r.rows.length === 0, 'other participant cannot read the note via RPC')
  r = await as(C, `select id from public.intro_outcomes`)
  ok(r.rows.length === 0, 'outsider sees no outcomes')
  r = await as(A, `update public.intro_outcomes set stage = 'outcome' returning id`)
  ok(!!r.error, 'outcomes are append-only (no update grant)')
  r = await as(A, `delete from public.intro_outcomes where author_id <> auth.uid() returning id`)
  ok(r.rows?.length === 0, 'cannot delete another participant outcome')
  r = await as('', `select id from public.intro_outcomes`)
  ok(!!r.error, 'anon has no access')

  console.log('check-ins')
  // The 40-day-old accepted intro (C → B) is due at the 30-day checkpoint for both participants.
  r = await as(B, `select * from public.my_due_outcome_checkins()`)
  const due = r.rows.find(x => x.intro_request_id === '11111111-1111-4111-8111-111111111111')
  ok(due && due.checkpoint === 30 && due.counterpart_id === C, 'target sees 30-day check-in with counterpart')
  ok(!r.rows.find(x => x.intro_request_id === intro), 'fresh intro not yet due (and terminal outcome recorded)')
  r = await as(B, `insert into public.intro_outcomes (intro_request_id, stage) values ('11111111-1111-4111-8111-111111111111', 'too_early')`)
  r = await as(B, `select * from public.my_due_outcome_checkins()`)
  ok(!r.rows.find(x => x.intro_request_id === '11111111-1111-4111-8111-111111111111'), 'recording a check-in clears it until the next checkpoint')
  r = await as(C, `select * from public.my_due_outcome_checkins()`)
  ok(r.rows.some(x => x.intro_request_id === '11111111-1111-4111-8111-111111111111'), 'other participant still owes their own check-in')
  r = await as(A, `select * from public.my_due_outcome_checkins()`)
  ok(!r.rows.some(x => x.intro_request_id === '11111111-1111-4111-8111-111111111111'), 'non-participant never sees it')

  console.log('proof metrics')
  r = await as(A, `select public.network_proof_metrics(90) as m`)
  ok(!!r.error, 'non-admin refused')
  r = await as(ADMIN, `select public.network_proof_metrics(90) as m`)
  const m = r.rows?.[0]?.m
  console.log('   ', JSON.stringify(m))
  ok(m && m.intros_requested === 3 && m.intros_accepted === 2 && m.intros_met === 1 && m.intros_outcome === 1 && m.outcomes_by_category.customer === 1, 'admin sees counts-only funnel')
}
