// @ts-nocheck
import {
  Person,
  Company,
  Opportunity,
  ActivityTask,
  CalendarEvent,
  MeetingDossier,
  MessageThread,
  SignalItem,
  KnowledgeDoc,
  ConnectionPathItem,
  ApprovalAction,
  IntroRecord,
  MemoryEvent,
  RuleAutomation,
  ExecutiveIntelligenceDossier,
  ActionableTaskItem,
  GraphNode,
  GraphLink,
  StructuredMeetingNote,
} from './types';

export const INITIAL_PEOPLE: Person[] = [
  {
    id: 'p-1',
    name: 'Elena Rostova',
    title: 'Managing Partner',
    company: 'Apex Capital',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    connectionScore: 94,
    scoreBreakdown: {
      recency: 96,
      frequency: 91,
      reciprocity: 92,
      mutuals: 97,
    },
    mutualsCount: 38,
    mutualAvatars: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    ],
    radarBucket: 'hot',
    engagement: 'active',
    tier: 'inner_circle',
    tags: ['Syndicate', 'Lead Investor', 'DeepTech', 'Apex Capital', 'Board'],
    email: 'elena@apexcap.vc',
    phone: '+1 (415) 890-2190',
    lastTouchpoint: 'Yesterday · Private Executive Dinner, SF',
    touchpointType: 'Dinner',
    notes: 'Key co-investor in Series B. Mutual trust built over 4 syndicated allocations.',
  },
  {
    id: 'p-2',
    name: 'Marcus Vance',
    title: 'Co-Founder & CEO',
    company: 'Vance Aerospace',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    connectionScore: 89,
    scoreBreakdown: { recency: 88, frequency: 90, reciprocity: 86, mutuals: 92 },
    mutualsCount: 24,
    mutualAvatars: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    ],
    radarBucket: 'hot',
    engagement: 'active',
    tier: 'inner_circle',
    tags: ['Defense', 'Aerospace', 'Autonomous', 'Founder', 'Series B'],
    email: 'marcus@vanceaero.com',
    lastTouchpoint: '3 days ago · Strategy Call',
    touchpointType: 'Call',
    notes: 'Expanding orbital defense sensors. Evaluating our enterprise suite.',
  },
  {
    id: 'p-3',
    name: 'Sophia Chen',
    title: 'Chief Information Officer',
    company: 'Nordic Sovereign Tech',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    connectionScore: 82,
    scoreBreakdown: { recency: 84, frequency: 78, reciprocity: 80, mutuals: 86 },
    mutualsCount: 19,
    mutualAvatars: [],
    radarBucket: 'emerging',
    engagement: 'active',
    tier: 'strategic',
    tags: ['Sovereign', 'Infrastructure', 'Europe', 'Allocations', 'LP'],
    email: 's.chen@nordicsov.org',
    lastTouchpoint: '5 days ago · Intro via David Sterling',
    touchpointType: 'Intro',
    notes: 'Overseeing €120M infrastructure mandate. High intent for trusted platforms.',
  },
  {
    id: 'p-4',
    name: 'David Sterling',
    title: 'General Partner',
    company: 'Benchmark Growth',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&auto=format&fit=crop&q=80',
    connectionScore: 96,
    scoreBreakdown: { recency: 98, frequency: 94, reciprocity: 96, mutuals: 98 },
    mutualsCount: 52,
    mutualAvatars: [],
    radarBucket: 'strategic',
    engagement: 'active',
    tier: 'inner_circle',
    tags: ['Growth', 'Silicon Valley', 'Anchor', 'Advisory', 'London'],
    email: 'sterling@benchmarkgrowth.com',
    lastTouchpoint: '1 week ago · Breakfast Briefing',
    touchpointType: 'Meeting',
    notes: 'Anchor connector into London & Silicon Valley LP circles.',
  },
  {
    id: 'p-5',
    name: 'Arthur Pendelton',
    title: 'Senior VP, Global Strategy',
    company: 'Horizon Health Systems',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80',
    connectionScore: 47,
    scoreBreakdown: { recency: 32, frequency: 40, reciprocity: 50, mutuals: 66 },
    mutualsCount: 11,
    mutualAvatars: [],
    radarBucket: 'at_risk',
    engagement: 'followup',
    tier: 'strategic',
    tags: ['Health Systems', 'Enterprise RFP', 'At-Risk', 'Procurement'],
    email: 'a.pendelton@horizonhealth.com',
    lastTouchpoint: '48 days ago · Unanswered email follow-up',
    touchpointType: 'Email',
    notes: 'No contact in 7 weeks. Major RFP deadline approaching.',
  },
  {
    id: 'p-6',
    name: 'Priya Sharma',
    title: 'Founder & CEO',
    company: 'NeoQuantum AI',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    connectionScore: 58,
    scoreBreakdown: { recency: 35, frequency: 52, reciprocity: 60, mutuals: 70 },
    mutualsCount: 16,
    mutualAvatars: [],
    radarBucket: 'dormant',
    engagement: 'dormant',
    tier: 'strategic',
    tags: ['Photonic', 'AI Compute', 'Founder', 'Hardware'],
    email: 'priya@neoquantum.ai',
    phone: '+1 (650) 412-9844',
    lastTouchpoint: '64 days ago · Quarterly Catch-up Call',
    touchpointType: 'Call',
    notes: 'Pioneering photonic compute. Relationship cooled after product pivot.',
  },
  {
    id: 'p-7',
    name: 'Elliot Croft',
    title: 'Head of Strategic Alliances',
    company: 'Kinetic Core',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    connectionScore: 88,
    scoreBreakdown: { recency: 92, frequency: 85, reciprocity: 88, mutuals: 84 },
    mutualsCount: 22,
    mutualAvatars: [],
    radarBucket: 'hot',
    engagement: 'active',
    tier: 'network',
    tags: ['Alliances', 'Co-Selling', 'Channel Partner', 'Network'],
    email: 'elliot@kineticcore.io',
    phone: '+1 (415) 309-8812',
    lastTouchpoint: '2 days ago · Co-selling Strategy Sync',
    touchpointType: 'Meeting',
    notes: 'High synergy with our executive tier. Exploring cross-platform channel agreement.',
  },
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'c-1',
    name: 'Apex Capital',
    domain: 'apexcap.vc',
    valuation: '$3.2B AUM',
    stage: 'Multi-Stage VC',
    sector: 'Deep Tech & FinTech',
    executivesCount: 14,
    openOpportunitiesValue: 1400000,
    signalsCount: 5,
    warmPathAvailable: true,
    notes: 'Lead Tier 1 Syndicate partner with strong portfolio governance.',
  },
  {
    id: 'c-2',
    name: 'Vance Aerospace',
    domain: 'vanceaero.com',
    valuation: '$820M',
    stage: 'Series C',
    sector: 'Defense & Autonomous Systems',
    executivesCount: 8,
    openOpportunitiesValue: 1800000,
    signalsCount: 4,
    warmPathAvailable: true,
    notes: 'Deploying high-reliability secure data networks for constellations.',
  },
  {
    id: 'c-3',
    name: 'Nordic Sovereign Tech',
    domain: 'nordicsov.org',
    valuation: 'Institutional',
    stage: 'Sovereign Fund',
    sector: 'European Critical Infrastructure',
    executivesCount: 22,
    openOpportunitiesValue: 850000,
    signalsCount: 6,
    warmPathAvailable: true,
    notes: 'Exploring sovereign data residency compliance partnerships.',
  },
  {
    id: 'c-4',
    name: 'Stripe Global Network',
    domain: 'stripe.com',
    valuation: '$70B',
    stage: 'Pre-IPO',
    sector: 'Financial Infrastructure',
    executivesCount: 42,
    openOpportunitiesValue: 750000,
    signalsCount: 9,
    warmPathAvailable: true,
    notes: 'Embedded relationship intelligence evaluation for executive teams.',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Nordic Sovereign Data Expansion',
    companyName: 'Nordic Sovereign Tech',
    stage: 'Discovery',
    value: 850000,
    currency: 'USD',
    attributedIntroId: 'intro-2',
    closeProbability: 40,
    targetQuarter: 'Q4 2026',
    leadPerson: 'Sophia Chen',
  },
  {
    id: 'opp-2',
    title: 'Apex Capital Portfolio Syndicate',
    companyName: 'Apex Capital',
    stage: 'Qualified',
    value: 1400000,
    currency: 'USD',
    attributedIntroId: 'intro-1',
    closeProbability: 70,
    targetQuarter: 'Q3 2026',
    leadPerson: 'Elena Rostova',
  },
  {
    id: 'opp-3',
    title: 'Vance Aerospace Mission Data Engine',
    companyName: 'Vance Aerospace',
    stage: 'Proposal',
    value: 1800000,
    currency: 'USD',
    attributedIntroId: 'intro-3',
    closeProbability: 85,
    targetQuarter: 'Q3 2026',
    leadPerson: 'Marcus Vance',
  },
  {
    id: 'opp-4',
    title: 'Stripe Enterprise Relationship Mesh',
    companyName: 'Stripe Global Network',
    stage: 'Closed',
    value: 750000,
    currency: 'USD',
    attributedIntroId: 'intro-4',
    closeProbability: 100,
    targetQuarter: 'Q2 2026',
    leadPerson: 'David Sterling',
  },
];

export const INITIAL_TASKS: ActivityTask[] = [
  {
    id: 't-1',
    title: 'Send Series B term sheet comments to Elena Rostova',
    dueDate: 'Today · 17:00',
    completed: false,
    priority: 'high',
    linkedPerson: 'Elena Rostova',
  },
  {
    id: 't-2',
    title: 'Sign off on Vance Aerospace security architecture appendix',
    dueDate: 'Tomorrow',
    completed: false,
    priority: 'high',
    linkedPerson: 'Marcus Vance',
  },
  {
    id: 't-3',
    title: 'Approve Digital You outbound intro draft for Sophia Chen',
    dueDate: 'Oct 6',
    completed: false,
    priority: 'medium',
    linkedPerson: 'Sophia Chen',
  },
  {
    id: 't-4',
    title: 'Review Zurich Sovereign Fund executive brief',
    dueDate: 'Oct 8',
    completed: false,
    priority: 'medium',
  },
];

export const INITIAL_CALENDAR: CalendarEvent[] = [
  {
    id: 'cal-1',
    time: '09:30 - 10:15',
    duration: '45m',
    meetingDate: 'Today · Upcoming in 42m',
    title: 'Series B Strategy & Syndicate Alignment',
    linkedPerson: 'Marcus Vance',
    company: 'Vance Aerospace',
    location: 'Aetheris Secure Bridge / Zoom 1',
    notes: 'Confirm valuation cap, payload orbital benchmarks, and lead syndicate investor rights before board circulation.',
    isPriority: true,
    priorityCategory: 'Syndicate Terms',
    attendees: [
      { name: 'Marcus Vance', title: 'CEO, Vance Aerospace' },
      { name: 'Elena Rostova', title: 'MP, Apex Capital' },
    ],
  },
  {
    id: 'cal-2',
    time: '11:00 - 11:45',
    duration: '45m',
    meetingDate: 'Today · 11:00',
    title: 'Sovereign Fund Mandate Briefing',
    linkedPerson: 'Sophia Chen',
    company: 'Nordic Sovereign Tech',
    location: 'Stockholm Video Suite',
    notes: 'Review European regulatory residency proof of concept and €120M infrastructure mandate parameters.',
    isPriority: true,
    priorityCategory: 'LP Allocation',
    attendees: [
      { name: 'Sophia Chen', title: 'CIO, Nordic Sovereign Tech' },
    ],
  },
  {
    id: 'cal-3',
    time: '14:15 - 15:00',
    duration: '45m',
    meetingDate: 'Today · 14:15',
    title: 'Techstars & UK Sovereign Channel Review',
    linkedPerson: 'David Sterling',
    company: 'Benchmark Growth',
    location: 'Sand Hill Rd / Private Suite',
    notes: 'Anchor syndicate introductions across European deep-tech cohort and growth fund allocations.',
    isPriority: true,
    priorityCategory: 'Strategic Partnership',
    attendees: [
      { name: 'David Sterling', title: 'GP, Benchmark Growth' },
    ],
  },
  {
    id: 'cal-4',
    time: '16:30 - 17:30',
    duration: '60m',
    meetingDate: 'Today · 16:30',
    title: 'Q4 Board Governance & Syndicate Capital Review',
    linkedPerson: 'Elena Rostova',
    company: 'Apex Capital',
    location: 'Executive Boardroom',
    notes: 'Pre-flight check on $850M Fund V allocations, audit committee findings, and pro-rata syndicate guarantees.',
    isPriority: true,
    priorityCategory: 'Board Mandate',
    attendees: [
      { name: 'Elena Rostova', title: 'Managing Partner, Apex Capital' },
      { name: 'David Sterling', title: 'GP, Benchmark Growth' },
    ],
  },
  {
    id: 'cal-5',
    time: '10:00 - 10:45',
    duration: '45m',
    meetingDate: 'Tomorrow · 10:00',
    title: 'Photonic Compute Deep-Tech Co-Investment Review',
    linkedPerson: 'Priya Sharma',
    company: 'NeoQuantum AI',
    location: 'Sand Hill Rd Conference Suite',
    notes: 'Evaluate 10x inference energy reduction benchmarks and bridge to Apex Fund V deep-tech allocation.',
    isPriority: true,
    priorityCategory: 'Syndicate Terms',
    attendees: [
      { name: 'Priya Sharma', title: 'CEO, NeoQuantum AI' },
      { name: 'Elena Rostova', title: 'MP, Apex Capital' },
    ],
  },
  {
    id: 'cal-6',
    time: '13:00 - 13:45',
    duration: '45m',
    meetingDate: 'Oct 8 · 13:00',
    title: 'Horizon Health Emergency Procurement Breakfast',
    linkedPerson: 'Arthur Pendelton',
    company: 'Horizon Health Systems',
    location: 'The Battery, San Francisco',
    notes: 'Urgent touchpoint addressing 48-day communication silence before enterprise network RFP shortlists finalize.',
    isPriority: true,
    priorityCategory: 'Strategic Partnership',
    attendees: [
      { name: 'Arthur Pendelton', title: 'SVP Global Strategy, Horizon Health' },
    ],
  },
  {
    id: 'cal-7',
    time: '15:00 - 15:45',
    duration: '45m',
    meetingDate: 'Oct 9 · 15:00',
    title: 'Enterprise Mesh Cross-Selling Alignment',
    linkedPerson: 'Elliot Croft',
    company: 'Kinetic Core',
    location: 'Kinetic HQ / Video Link',
    notes: 'Structure joint distribution agreement and map enterprise account overlap across Fortune 500 clouds.',
    isPriority: false,
    priorityCategory: 'Strategic Partnership',
    attendees: [
      { name: 'Elliot Croft', title: 'Head of Strategic Alliances, Kinetic Core' },
    ],
  },
];

export const INITIAL_MEETING: MeetingDossier = {
  id: 'meet-1',
  title: 'Series B Strategy & Syndicate Alignment',
  time: 'Next up: 09:30 (in 42m)',
  attendees: [
    {
      name: 'Marcus Vance',
      title: 'CEO, Vance Aerospace',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      score: 89,
    },
    {
      name: 'Elena Rostova',
      title: 'Managing Partner, Apex',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
      score: 94,
    },
  ],
  notesCount: 6,
  decisions: [
    'Syndicate allocations capped at $28M hard ceiling.',
    'Lead terms validated against Benchmark comparison index.',
  ],
  actionItems: [
    'Elena to circulate updated co-sale covenants by noon.',
    'Send technical annex to Vance engineering committee.',
  ],
  followups: [
    'Automated intro handoff to CFO for KYC filings.',
  ],
  status: 'upcoming',
};

export const INITIAL_THREADS: MessageThread[] = [
  {
    id: 'msg-1',
    sender: 'Elena Rostova',
    company: 'Apex Capital',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    subject: 'Syndicate participation memo ready for review',
    preview: 'I have finalized the co-investment structure with the Geneva family office...',
    timestamp: '14m ago',
    type: 'email',
    unread: true,
    strategicWeight: 'high',
  },
  {
    id: 'msg-2',
    sender: 'Sophia Chen',
    company: 'Nordic Sovereign Tech',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    subject: 'Pre-meeting thoughts on sovereign compliance',
    preview: 'Our legal team approved the cross-border architecture preliminary note...',
    timestamp: '2h ago',
    type: 'message',
    unread: false,
    strategicWeight: 'high',
  },
  {
    id: 'msg-3',
    sender: 'David Sterling',
    company: 'Benchmark Growth',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    subject: 'Warm path confirmed for Satya & London LPs',
    preview: 'Spoke with him yesterday over dinner. He is receptive to an introduction next Tuesday...',
    timestamp: '4h ago',
    type: 'email',
    unread: false,
    strategicWeight: 'medium',
  },
];

export const INITIAL_SIGNALS: SignalItem[] = [
  {
    id: 'sig-1',
    type: 'Looking For',
    actor: 'Elena Rostova',
    role: 'Managing Partner',
    company: 'Apex Capital',
    headline: 'Seeking enterprise AI infrastructure leads for $15M lead check',
    timestamp: '1h ago',
    matchScore: 98,
  },
  {
    id: 'sig-2',
    type: 'Offering',
    actor: 'David Sterling',
    role: 'GP',
    company: 'Benchmark Growth',
    headline: 'Offering syndicated co-investment rights in Series B aerospace asset',
    timestamp: '3h ago',
    matchScore: 94,
  },
  {
    id: 'sig-3',
    type: 'Capital',
    actor: 'Sophia Chen',
    role: 'CIO',
    company: 'Nordic Sovereign Tech',
    headline: 'Deploying €50M sovereign resilience allocation before year-end',
    timestamp: '5h ago',
    matchScore: 91,
  },
  {
    id: 'sig-4',
    type: 'Talent',
    actor: 'Marcus Vance',
    role: 'CEO',
    company: 'Vance Aerospace',
    headline: 'Recruiting Chief Systems Architect (ex-Palantir / Space Force)',
    timestamp: '1d ago',
    matchScore: 89,
  },
  {
    id: 'sig-5',
    type: 'Partnership',
    actor: 'Arthur Pendelton',
    role: 'SVP Strategy',
    company: 'Horizon Health',
    headline: 'Seeking sovereign-grade private cloud integrations for healthcare telemetry',
    timestamp: '1d ago',
    matchScore: 82,
  },
  {
    id: 'sig-6',
    type: 'Acquisition',
    actor: 'Stripe Strategic M&A',
    role: 'Corporate Dev',
    company: 'Stripe',
    headline: 'Actively scouting relationship data pipelines & identity resolution teams',
    timestamp: '2d ago',
    matchScore: 88,
  },
  {
    id: 'sig-7',
    type: 'Insight',
    actor: 'Elena Rostova',
    role: 'Apex Research',
    company: 'Apex Capital',
    headline: 'Confidential benchmark: LP return expectations shift to private credit in Q4',
    timestamp: '2d ago',
    matchScore: 95,
  },
  {
    id: 'sig-8',
    type: 'Opportunity',
    actor: 'Nordic Sovereign Tech',
    role: 'Procurement Board',
    company: 'Nordic Sovereign',
    headline: 'RFP released for zero-trust executive collaboration mesh',
    timestamp: '3d ago',
    matchScore: 96,
  },
];

export const INITIAL_KNOWLEDGE_DOCS: KnowledgeDoc[] = [
  {
    id: 'k-1',
    title: 'Apex Capital — Fund V Mandate & Co-Investment Rights',
    folder: 'Company Briefs',
    dateAdded: 'Oct 02, 2026',
    excerpt: 'Detailed governance requirements, side-letter thresholds, and preferred liquidity timelines.',
    size: '240 KB',
  },
  {
    id: 'k-2',
    title: 'Series B Syndicate Alignment Session Minutes',
    folder: 'Meeting Notes',
    dateAdded: 'Oct 03, 2026',
    excerpt: 'Verbatim consensus reached on cap table dilution and founder voting super-majority.',
    size: '128 KB',
  },
  {
    id: 'k-3',
    title: 'European Sovereign Tech Resilience Audit 2026',
    folder: 'Research & Insights',
    dateAdded: 'Sep 28, 2026',
    excerpt: 'Macro analysis of data sovereignty statutes and sovereign fund allocation vectors.',
    size: '1.4 MB',
  },
  {
    id: 'k-4',
    title: 'Executive Master Services Agreement — Enterprise Tier',
    folder: 'Documents',
    dateAdded: 'Sep 15, 2026',
    excerpt: 'Standardized mutual NDA and enterprise license terms pre-approved by outside counsel.',
    size: '512 KB',
  },
  {
    id: 'k-5',
    title: 'Double Opt-In Introduction Playbook for Sovereign LPs',
    folder: 'Playbooks',
    dateAdded: 'Aug 20, 2026',
    excerpt: 'Step-by-step protocol for high-touch introductions without burning social capital.',
    size: '95 KB',
  },
  {
    id: 'k-6',
    title: 'Benchmark Growth LP Dinner Notes & Strategic Intelligences',
    folder: 'Saved Content',
    dateAdded: 'Oct 01, 2026',
    excerpt: 'Key commentary from 18 institutional allocators during the private Chatham House dinner.',
    size: '340 KB',
  },
];

export const INITIAL_INTROS: IntroRecord[] = [
  {
    id: 'intro-1',
    partyA: {
      name: 'Elena Rostova',
      title: 'Managing Partner',
      company: 'Apex Capital',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    },
    partyB: {
      name: 'Marcus Vance',
      title: 'CEO',
      company: 'Vance Aerospace',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    },
    stage: 3, // 1: Context Shared, 2: Both Parties Interested, 3: Meeting Scheduled, 4: Handoff Complete
    statusLabel: 'Meeting Scheduled (Thursday 14:00)',
    context: 'Syndicate lead introduction for Series B deep tech round ($15M lead commitment).',
    updatedAt: '2h ago',
  },
  {
    id: 'intro-2',
    partyA: {
      name: 'David Sterling',
      title: 'General Partner',
      company: 'Benchmark Growth',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
    },
    partyB: {
      name: 'Sophia Chen',
      title: 'CIO',
      company: 'Nordic Sovereign Tech',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    },
    stage: 4,
    statusLabel: 'Handoff Complete · Active Deal Created',
    context: 'Direct sovereign infrastructure mandate consultation.',
    updatedAt: 'Yesterday',
  },
  {
    id: 'intro-3',
    partyA: {
      name: 'You (CEO)',
      title: 'Chief Executive Officer',
      company: 'Aetheris Intros',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    },
    partyB: {
      name: 'Arthur Pendelton',
      title: 'SVP Strategy',
      company: 'Horizon Health',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    },
    stage: 2,
    statusLabel: 'Both Parties Interested (Awaiting Slot)',
    context: 'Enterprise telemetry contract re-engagement.',
    updatedAt: '3d ago',
  },
];

export const INITIAL_APPROVALS: ApprovalAction[] = [
  {
    id: 'appr-1',
    originTile: 'Digital You',
    actionType: 'Send Email',
    recipient: 'Elena Rostova (Apex Capital)',
    summary: 'Executive follow-up synthesizing Series B syndicate terms & valuation covenants.',
    fullDraft: 'Elena, great dining yesterday in SF. Regarding our Syndicate discussion: we have formalized the $28M hard cap with lead governance terms aligned to Benchmark standards. Looking forward to tomorrow morning at 09:30.',
    status: 'pending',
    createdTime: '18m ago',
  },
  {
    id: 'appr-2',
    originTile: 'Automations',
    actionType: 'Forward Intro',
    recipient: 'David Sterling → Satya N.',
    summary: 'Bilateral context memo for enterprise relationship mesh consultation.',
    fullDraft: 'David, thank you for agreeing to bridge us to Satya. Enclosed is our 2-page brief on how sovereign relationship intelligence is being adopted across Tier 1 aerospace and sovereign funds.',
    status: 'pending',
    createdTime: '1h ago',
  },
  {
    id: 'appr-3',
    originTile: 'Growth Studio',
    actionType: 'Publish Script',
    recipient: 'LP Quarterly Syndicate Circle',
    summary: 'Quarterly Executive Perspective on Private Sovereign Capital Inflows (Oct 2026).',
    fullDraft: 'Quarterly Perspective: While liquid public markets face volatility, sovereign allocators in Zurich and Stockholm are systematically increasing multi-year allocations to verified deep tech networks...',
    status: 'pending',
    createdTime: '3h ago',
  },
];

export const INITIAL_MEMORIES: MemoryEvent[] = [
  {
    id: 'mem-1',
    personName: 'Elena Rostova',
    date: 'Oct 03, 2026',
    title: 'Private Executive Dinner at The Battery, SF',
    description: 'Agreed on syndicated co-investment terms for Series B ($15M check). Mutual conviction high.',
    type: 'milestone',
    sentiment: 'positive',
  },
  {
    id: 'mem-2',
    personName: 'Marcus Vance',
    date: 'Sep 29, 2026',
    title: 'Closed Enterprise Agreement v2',
    description: 'Signed 2-year defense data constellation contract valued at $1.8M ARR.',
    type: 'deal',
    sentiment: 'positive',
  },
  {
    id: 'mem-3',
    personName: 'Sophia Chen',
    date: 'Sep 24, 2026',
    title: 'Warm Introduction completed via David Sterling',
    description: 'Both parties accepted double opt-in protocol within 4 hours. Shared sovereign whitepaper.',
    type: 'intro',
    sentiment: 'positive',
  },
  {
    id: 'mem-4',
    personName: 'Arthur Pendelton',
    date: 'Aug 14, 2026',
    title: 'Annual RFP Strategy Workshop',
    description: 'Initial scope presented. Arthur flagged legal review delays on data localization.',
    type: 'meeting',
    sentiment: 'neutral',
  },
];

export const INITIAL_AUTOMATIONS: RuleAutomation[] = [
  {
    id: 'auto-1',
    trigger: 'New Meeting Scheduled with Tier 1 CEO',
    relationshipCondition: 'Connection Score ≥ 85',
    action: 'Generate Pre-Meeting Brief & Cross-Graph Signals',
    followUp: 'Enqueue Approval Draft 2h before meeting',
    active: true,
    executionsCount: 42,
  },
  {
    id: 'auto-2',
    trigger: 'Touchpoint Gap Exceeds 30 Days',
    relationshipCondition: 'Strategic Radar Bucket',
    action: 'Synthesize Relevant Peer Signal or News',
    followUp: 'Present Re-engagement Draft to Approval Queue',
    active: true,
    executionsCount: 19,
  },
  {
    id: 'auto-3',
    trigger: 'Both Parties Accept Intro',
    relationshipCondition: 'Verified Double Opt-In',
    action: 'Create Calendar Placeholder & Shared Context Doc',
    followUp: 'Log to Relationship Memory & Notify Lead Partner',
    active: true,
    executionsCount: 31,
  },
];

export const INITIAL_GRID_SHEET = [
  { id: '1', founder: 'Elena Rostova', firm: 'Apex Capital', stage: 'Fund V', valuation: '$3.2B', introStatus: 'Active', conviction: '9.8 / 10' },
  { id: '2', founder: 'Marcus Vance', firm: 'Vance Aerospace', stage: 'Series B', valuation: '$820M', introStatus: 'Syndicated', conviction: '9.4 / 10' },
  { id: '3', founder: 'Sophia Chen', firm: 'Nordic Sovereign', stage: 'Gov Allocator', valuation: '€500M', introStatus: 'Meeting Set', conviction: '9.1 / 10' },
  { id: '4', founder: 'David Sterling', firm: 'Benchmark Growth', stage: 'GP Anchor', valuation: '$4.1B', introStatus: 'Verified Bridge', conviction: '9.9 / 10' },
  { id: '5', founder: 'Arthur Pendelton', firm: 'Horizon Health', stage: 'Enterprise', valuation: '$1.4B', introStatus: 'At Risk', conviction: '6.2 / 10' },
];

export const INITIAL_CONNECTION_PATHS: ConnectionPathItem[] = [
  {
    targetId: 'satya-1',
    targetName: 'Satya Nadella',
    targetTitle: 'Chairman & CEO',
    targetCompany: 'Microsoft',
    connectorName: 'David Sterling',
    connectorTitle: 'Founding General Partner, Benchmark',
    pathStrength: 98,
    degrees: 2,
  },
  {
    targetId: 'jensen-1',
    targetName: 'Jensen Huang',
    targetTitle: 'President & CEO',
    targetCompany: 'NVIDIA',
    connectorName: 'Elena Rostova',
    connectorTitle: 'Managing Partner, Apex Capital',
    pathStrength: 94,
    degrees: 2,
  },
  {
    targetId: 'patrick-1',
    targetName: 'Patrick Collison',
    targetTitle: 'CEO & Co-Founder',
    targetCompany: 'Stripe',
    connectorName: 'Marcus Vance',
    connectorTitle: 'CEO, Vance Aerospace',
    pathStrength: 91,
    degrees: 2,
  },
];

export const EXECUTIVE_INTELLIGENCE_DOSSIERS: Record<string, ExecutiveIntelligenceDossier> = {
  'p-1': {
    personId: 'p-1',
    personName: 'Elena Rostova',
    title: 'Managing Partner',
    company: 'Apex Capital',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    bio: 'Managing Partner at Apex Capital leading Fund V ($3.2B AUM). Specializes in syndicating deep-tech and enterprise mesh platforms with Tier 1 sovereign funds.',
    currentFocus: 'Closing the $140M Series B syndicate and structuring European co-investment allocations.',
    keyPriorities: [
      'Series B term sheet review with governance board',
      'Syndicating allocation rights to Nordic Sovereign Tech',
      'Q4 board preparation and revenue audits',
    ],
    sharedConnections: 38,
    activeDealsCount: 2,
    pipelineExposure: 1400000,
    recommendedAction: 'Send updated governance rider comments before 17:00 today.',
    lastTouchpoint: 'Yesterday · Private Executive Dinner, SF',
    engagement: 'active',
    connectionScore: 94,
    recentNews: [
      {
        id: 'news-1',
        title: 'Apex Capital announces first close of $850M Deep Tech Infrastructure Fund V',
        source: 'Financial Times',
        date: 'Yesterday',
        category: 'Funding',
        summary: 'Targeting next-generation enterprise protocols and sovereign compute fabrics across North America and Western Europe.',
        sentiment: 'bullish',
      },
      {
        id: 'news-2',
        title: 'Elena Rostova appointed to Global Sovereign AI Governance Council in Geneva',
        source: 'Bloomberg Technology',
        date: '4 days ago',
        category: 'Leadership',
        summary: 'Will advise multilateral allocators on relationship integrity protocols and institutional security standards.',
        sentiment: 'bullish',
      },
      {
        id: 'news-3',
        title: 'Venture syndicate volume shifts heavily toward CEO-operated trust networks',
        source: 'Wall Street Journal',
        date: '1 week ago',
        category: 'Market Insight',
        summary: 'Direct relationship capital outperforms open-market auctions by 3.4x in Series B closing speed.',
        sentiment: 'neutral',
      },
    ],
  },
  'p-2': {
    personId: 'p-2',
    personName: 'Marcus Vance',
    title: 'Co-Founder & CEO',
    company: 'Vance Aerospace',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    bio: 'Co-Founder & CEO of Vance Aerospace ($820M valuation). Former NASA JPL flight dynamics engineer building low-earth orbit sensor meshes.',
    currentFocus: 'Deploying high-reliability secure data networks for next-gen orbital constellation constellations.',
    keyPriorities: [
      'Security architecture appendix sign-off',
      'Series C growth bridge allocation',
      'Defense department data protocol integration',
    ],
    sharedConnections: 24,
    activeDealsCount: 1,
    pipelineExposure: 1800000,
    recommendedAction: 'Sign off on security architecture appendix appendix t-2.',
    lastTouchpoint: '3 days ago · Strategy Call',
    engagement: 'active',
    connectionScore: 89,
    recentNews: [
      {
        id: 'news-4',
        title: 'Vance Aerospace secures $42M multi-orbit telemetry defense contract',
        source: 'DefenseNews',
        date: '3 days ago',
        category: 'Strategic Partnership',
        summary: 'Contract expands satellite edge mesh compute capabilities into secure federal communication layers.',
        sentiment: 'bullish',
      },
      {
        id: 'news-5',
        title: 'Marcus Vance keynote at Space Economy Summit: The Autonomous Orbit',
        source: 'Aviation Week',
        date: '6 days ago',
        category: 'Leadership',
        summary: 'Highlighting decentralized ground station handoffs and low-latency executive communication meshes.',
        sentiment: 'neutral',
      },
    ],
  },
  'p-3': {
    personId: 'p-3',
    personName: 'Sophia Chen',
    title: 'Chief Information Officer',
    company: 'Nordic Sovereign Tech',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    bio: 'CIO at Nordic Sovereign Tech managing €120M infrastructure mandate. Specialist in EU data sovereignty and zero-trust institutional fabrics.',
    currentFocus: 'Reviewing cross-border relationship intelligence platforms for European institutional allocators.',
    keyPriorities: [
      'European regulatory data residency validation',
      'Briefing with David Sterling on Sand Hill Road syndicate',
    ],
    sharedConnections: 19,
    activeDealsCount: 1,
    pipelineExposure: 850000,
    recommendedAction: 'Prepare residency compliance proof of concept before upcoming briefing.',
    lastTouchpoint: '5 days ago · Intro via David Sterling',
    engagement: 'active',
    connectionScore: 82,
    recentNews: [
      {
        id: 'news-6',
        title: 'Nordic Sovereign Fund earmarks €1.2B for resilient digital infrastructure',
        source: 'Reuters European Markets',
        date: '4 days ago',
        category: 'Funding',
        summary: 'Prioritizing audited relationship software and sovereign identity vaults with high auditability.',
        sentiment: 'bullish',
      },
      {
        id: 'news-7',
        title: 'EU directive takes effect on cross-border institutional relationship transparency',
        source: 'Euractiv',
        date: '1 week ago',
        category: 'Regulatory',
        summary: 'Demands full verification trails for executive syndication channels and LP introductions.',
        sentiment: 'watch',
      },
    ],
  },
  'p-4': {
    personId: 'p-4',
    personName: 'David Sterling',
    title: 'General Partner',
    company: 'Benchmark Growth',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&auto=format&fit=crop&q=80',
    bio: 'Founding General Partner at Benchmark Growth. Anchor connector into Sand Hill Road, London venture circles, and top institutional buyers.',
    currentFocus: 'Anchor connector into London & Silicon Valley LP circles, advising Series B and growth-stage founders.',
    keyPriorities: [
      'Techstars Global Advisory Sync mentor matching',
      'Warm bridge intro to Microsoft executive leadership',
    ],
    sharedConnections: 52,
    activeDealsCount: 1,
    pipelineExposure: 750000,
    recommendedAction: 'Sync on mentor allocations following breakfast briefing.',
    lastTouchpoint: '1 week ago · Breakfast Briefing',
    engagement: 'active',
    connectionScore: 96,
    recentNews: [
      {
        id: 'news-8',
        title: 'Benchmark Growth expands executive operator bench with 6 partner promotions',
        source: 'VentureBeat',
        date: '3 days ago',
        category: 'Leadership',
        summary: 'Strengthening early-stage conviction and cross-portfolio syndicate networks.',
        sentiment: 'bullish',
      },
    ],
  },
  'p-5': {
    personId: 'p-5',
    personName: 'Arthur Pendelton',
    title: 'Senior VP, Global Strategy',
    company: 'Horizon Health Systems',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80',
    bio: 'Senior VP, Global Strategy at Horizon Health Systems ($1.4B enterprise hospital network). 48-day communication drift detected.',
    currentFocus: 'Evaluating patient data relationship architectures and enterprise provider communications.',
    keyPriorities: [
      'Overcoming 48d unanswered email drift',
      'Addressing pending RFP deadline before Q4 close',
    ],
    sharedConnections: 11,
    activeDealsCount: 0,
    pipelineExposure: 0,
    recommendedAction: 'Urgent: Schedule breakfast meeting via mutual connection David Sterling.',
    lastTouchpoint: '48 days ago · Unanswered email follow-up',
    engagement: 'followup',
    connectionScore: 47,
    recentNews: [
      {
        id: 'news-9',
        title: 'Horizon Health initiates competitive vendor RFP for communications overhaul',
        source: 'Healthcare IT News',
        date: '12 days ago',
        category: 'M&A',
        summary: 'Health system seeking modern platforms to streamline physician-to-executive communication.',
        sentiment: 'watch',
      },
    ],
  },
  'p-6': {
    personId: 'p-6',
    personName: 'Priya Sharma',
    title: 'Founder & CEO',
    company: 'NeoQuantum AI',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    bio: 'Founder & CEO of NeoQuantum AI. Pioneer in photonic neural compute. Relationship currently in dormant state (64d drift).',
    currentFocus: 'Commercializing ultra-low latency optical neural network accelerators for AI clusters.',
    keyPriorities: [
      'Quarterly relationship re-engagement call',
      'Exploring photonics co-development syndicate',
    ],
    sharedConnections: 16,
    activeDealsCount: 0,
    pipelineExposure: 0,
    recommendedAction: 'Send informal check-in regarding recent photonic compute benchmarks.',
    lastTouchpoint: '64 days ago · Quarterly Catch-up Call',
    engagement: 'dormant',
    connectionScore: 58,
    recentNews: [
      {
        id: 'news-10',
        title: 'NeoQuantum AI demonstrates 10x energy reduction in photonic inference chip',
        source: 'IEEE Spectrum',
        date: '1 week ago',
        category: 'Market Insight',
        summary: 'Silicon-photonic coprocessor sets new efficiency benchmark for transformer token generation.',
        sentiment: 'bullish',
      },
    ],
  },
  'p-7': {
    personId: 'p-7',
    personName: 'Elliot Croft',
    title: 'Head of Strategic Alliances',
    company: 'Kinetic Core',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    bio: 'Head of Strategic Alliances at Kinetic Core. Leading cross-platform co-selling and enterprise executive distribution agreements.',
    currentFocus: 'Drafting channel partnership terms and joint enterprise go-to-market plan.',
    keyPriorities: [
      'Finalizing co-selling agreement draft',
      'Alignment on enterprise revenue share percentages',
    ],
    sharedConnections: 22,
    activeDealsCount: 1,
    pipelineExposure: 500000,
    recommendedAction: 'Review channel agreement appendix before tomorrow afternoon.',
    lastTouchpoint: '2 days ago · Co-selling Strategy Sync',
    engagement: 'active',
    connectionScore: 88,
    recentNews: [
      {
        id: 'news-11',
        title: 'Kinetic Core forms strategic alliance with global systems integration leaders',
        source: 'Enterprise Tech',
        date: '4 days ago',
        category: 'Strategic Partnership',
        summary: 'Alliance accelerates enterprise distribution into Fortune 500 industrial accounts.',
        sentiment: 'bullish',
      },
    ],
  },
};

export const INITIAL_ACTIONABLE_TASKS: ActionableTaskItem[] = [
  {
    id: 'act-1',
    sourceTile: 'tasks-work',
    sourceTileTitle: 'Tasks & Work',
    title: 'Send Series B term sheet comments to Elena Rostova',
    description: 'Ensure valuation cap and syndication co-investment rights align with board expectations.',
    type: 'commitment',
    priority: 'high',
    dueDate: 'Today · 17:00',
    completed: false,
    linkedPerson: 'Elena Rostova',
    linkedCompany: 'Apex Capital',
    actionLabel: 'Review Term Sheet',
  },
  {
    id: 'act-2',
    sourceTile: 'tasks-work',
    sourceTileTitle: 'Tasks & Work',
    title: 'Sign off on Vance Aerospace security architecture appendix',
    description: 'Review low-earth orbit data encryption protocols for sensor telemetry integration.',
    type: 'commitment',
    priority: 'high',
    dueDate: 'Tomorrow',
    completed: false,
    linkedPerson: 'Marcus Vance',
    linkedCompany: 'Vance Aerospace',
    actionLabel: 'Sign Appendix',
  },
  {
    id: 'act-3',
    sourceTile: 'digital-you',
    sourceTileTitle: 'Digital You (Approvals)',
    title: 'Executive Twin: Approve intro follow-up draft for Elena Rostova',
    description: 'Synthesized warm intro thank-you note referencing private dinner conversations.',
    type: 'approval',
    priority: 'high',
    dueDate: 'Today · Urgent',
    completed: false,
    linkedPerson: 'Elena Rostova',
    linkedCompany: 'Apex Capital',
    actionLabel: 'Review Draft',
  },
  {
    id: 'act-4',
    sourceTile: 'digital-you',
    sourceTileTitle: 'Digital You (Approvals)',
    title: 'Executive Twin: Approve outbound briefing memo for Sophia Chen',
    description: 'Pre-flight dossier covering European data residency architecture for upcoming sync.',
    type: 'approval',
    priority: 'medium',
    dueDate: 'Oct 6',
    completed: false,
    linkedPerson: 'Sophia Chen',
    linkedCompany: 'Nordic Sovereign Tech',
    actionLabel: 'Approve Dispatch',
  },
  {
    id: 'act-5',
    sourceTile: 'relationship-radar',
    sourceTileTitle: 'Relationship Radar',
    title: 'Arthur Pendelton: Address 48-day communication drift',
    description: 'Unanswered follow-up email 7 weeks ago. Horizon Health RFP deadline approaching.',
    type: 'followup_drift',
    priority: 'high',
    dueDate: 'Immediate Action Needed',
    completed: false,
    linkedPerson: 'Arthur Pendelton',
    linkedCompany: 'Horizon Health Systems',
    actionLabel: 'Schedule Touchpoint',
  },
  {
    id: 'act-6',
    sourceTile: 'tasks-work',
    sourceTileTitle: 'Tasks & Work',
    title: 'Review Zurich Sovereign Fund executive brief',
    description: 'Synthesized allocation memo outlining €120M co-investment mandate.',
    type: 'commitment',
    priority: 'medium',
    dueDate: 'Oct 8',
    completed: false,
    actionLabel: 'Open Brief',
  },
  {
    id: 'act-7',
    sourceTile: 'introductions',
    sourceTileTitle: 'Introductions',
    title: 'Double Opt-In Intro: Sarah Mitchell & Elena Rostova',
    description: 'Both parties expressed high interest. Handoff meeting confirmation pending.',
    type: 'intro_optin',
    priority: 'medium',
    dueDate: 'Oct 7',
    completed: false,
    linkedPerson: 'Elena Rostova',
    actionLabel: 'Confirm Handoff',
  },
  {
    id: 'act-8',
    sourceTile: 'relationship-radar',
    sourceTileTitle: 'Relationship Radar',
    title: 'Priya Sharma: Quarterly reconnection catch-up',
    description: '64d touchpoint drift. Recent breakthroughs in optical neural acceleration.',
    type: 'followup_drift',
    priority: 'low',
    dueDate: 'Oct 9',
    completed: false,
    linkedPerson: 'Priya Sharma',
    linkedCompany: 'NeoQuantum AI',
    actionLabel: 'Send Check-in',
  },
];

export const INITIAL_GRAPH_NODES: GraphNode[] = [
  {
    id: 'p-1',
    name: 'Elena Rostova',
    title: 'Managing Partner',
    company: 'Apex Capital',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    cluster: 'capital',
    clusterLabel: 'Capital & Syndicates',
    connectionScore: 94,
    engagement: 'active',
    val: 28,
  },
  {
    id: 'p-2',
    name: 'Marcus Vance',
    title: 'CEO & Co-Founder',
    company: 'Vance Aerospace',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    cluster: 'aerospace',
    clusterLabel: 'Deep Tech & Aerospace',
    connectionScore: 89,
    engagement: 'active',
    val: 24,
  },
  {
    id: 'p-3',
    name: 'Sophia Chen',
    title: 'Chief Information Officer',
    company: 'Nordic Sovereign Tech',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    cluster: 'sovereign',
    clusterLabel: 'Sovereign & Gov Allocators',
    connectionScore: 82,
    engagement: 'active',
    val: 22,
  },
  {
    id: 'p-4',
    name: 'David Sterling',
    title: 'General Partner',
    company: 'Benchmark Growth',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&auto=format&fit=crop&q=80',
    cluster: 'capital',
    clusterLabel: 'Capital & Syndicates',
    connectionScore: 96,
    engagement: 'active',
    val: 30,
  },
  {
    id: 'p-5',
    name: 'Arthur Pendelton',
    title: 'Senior VP, Global Strategy',
    company: 'Horizon Health',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80',
    cluster: 'enterprise',
    clusterLabel: 'Enterprise Strategy',
    connectionScore: 47,
    engagement: 'followup',
    val: 16,
  },
  {
    id: 'p-6',
    name: 'Priya Sharma',
    title: 'Founder & CEO',
    company: 'NeoQuantum AI',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    cluster: 'ai_deeptech',
    clusterLabel: 'AI & Photonics',
    connectionScore: 58,
    engagement: 'dormant',
    val: 18,
  },
  {
    id: 'p-7',
    name: 'Elliot Croft',
    title: 'Head of Strategic Alliances',
    company: 'Kinetic Core',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    cluster: 'enterprise',
    clusterLabel: 'Enterprise Strategy',
    connectionScore: 88,
    engagement: 'active',
    val: 20,
  },
  {
    id: 'satya',
    name: 'Satya Nadella',
    title: 'Chairman & CEO',
    company: 'Microsoft',
    cluster: 'enterprise',
    clusterLabel: 'Enterprise Strategy',
    connectionScore: 85,
    engagement: 'active',
    val: 22,
  },
  {
    id: 'jensen',
    name: 'Jensen Huang',
    title: 'President & CEO',
    company: 'NVIDIA',
    cluster: 'ai_deeptech',
    clusterLabel: 'AI & Photonics',
    connectionScore: 92,
    engagement: 'active',
    val: 26,
  },
  {
    id: 'patrick',
    name: 'Patrick Collison',
    title: 'CEO & Co-Founder',
    company: 'Stripe',
    cluster: 'capital',
    clusterLabel: 'Capital & Syndicates',
    connectionScore: 90,
    engagement: 'active',
    val: 24,
  },
  {
    id: 'summit',
    name: 'Sarah Mitchell',
    title: 'CEO',
    company: 'Summit Capital',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    cluster: 'capital',
    clusterLabel: 'Capital & Syndicates',
    connectionScore: 78,
    engagement: 'active',
    val: 16,
  },
  {
    id: 'vector',
    name: 'James Park',
    title: 'Founder',
    company: 'Vector Labs',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    cluster: 'ai_deeptech',
    clusterLabel: 'AI & Photonics',
    connectionScore: 81,
    engagement: 'active',
    val: 18,
  },
];

export const INITIAL_GRAPH_LINKS: GraphLink[] = [
  { source: 'p-1', target: 'p-2', strength: 0.9, relationshipType: 'syndicate' },
  { source: 'p-1', target: 'p-4', strength: 0.95, relationshipType: 'trusted_peer' },
  { source: 'p-1', target: 'p-3', strength: 0.75, relationshipType: 'mandate' },
  { source: 'p-1', target: 'jensen', strength: 0.85, relationshipType: 'syndicate' },
  { source: 'p-1', target: 'summit', strength: 0.7, relationshipType: 'syndicate' },
  { source: 'p-2', target: 'p-7', strength: 0.85, relationshipType: 'portfolio' },
  { source: 'p-2', target: 'patrick', strength: 0.8, relationshipType: 'trusted_peer' },
  { source: 'p-3', target: 'p-4', strength: 0.85, relationshipType: 'trusted_peer' },
  { source: 'p-4', target: 'satya', strength: 0.9, relationshipType: 'trusted_peer' },
  { source: 'p-4', target: 'p-5', strength: 0.6, relationshipType: 'advisory' },
  { source: 'p-6', target: 'jensen', strength: 0.75, relationshipType: 'portfolio' },
  { source: 'p-6', target: 'vector', strength: 0.8, relationshipType: 'trusted_peer' },
  { source: 'p-7', target: 'satya', strength: 0.65, relationshipType: 'advisory' },
  { source: 'vector', target: 'jensen', strength: 0.7, relationshipType: 'portfolio' },
];

export const INITIAL_MEETING_NOTES: Record<string, StructuredMeetingNote[]> = {
  'p-1': [
    {
      id: 'note-elena-1',
      personId: 'p-1',
      title: 'Series B Syndicate Alignment & Allocation Governance',
      category: 'meeting_minutes',
      createdAt: 'Oct 4, 2026 · 19:30 PST',
      tags: ['Series B', 'Governance', 'Apex Fund V'],
      actionItems: [
        'Deliver finalized capitalization model by 17:00 today',
        'Bridge Sophia Chen (Nordic Sovereign) to Fund V deep-tech allocation',
        'Confirm board observer seats for lead syndicate',
      ],
      content: `## Executive Briefing Minutes
**Location:** Private Dining Room, St. Regis SF
**Attendees:** Elena Rostova (Apex Capital), Alexander Cross (Aetheris CEO)

### Key Strategic Discussion
- Elena confirmed Apex Fund V will anchor **$42M** of the syndicated round with pro-rata rights.
- Addressed cross-cluster telemetry with Vance Aerospace; Elena favors direct sovereign co-investment.
- Board alignment: Elena requests 1 governance board seat and 1 observer seat for deep-tech syndication.

### Tactical Action Items
- [ ] Deliver finalized capitalization model by 17:00 today
- [ ] Bridge Sophia Chen (Nordic Sovereign) to Fund V deep-tech allocation
- [ ] Schedule Q4 board preparatory review before Nov 12`,
    },
    {
      id: 'note-elena-2',
      personId: 'p-1',
      title: 'Tactical Brief: NVIDIA Compute Partnership Leverage',
      category: 'tactical_note',
      createdAt: 'Sept 28, 2026 · 11:15 PST',
      tags: ['Tactical', 'GPU Allocation', 'Jensen Huang Bridge'],
      actionItems: ['Coordinate joint introduction packet for Jensen Huang team'],
      content: `## Tactical Deal Note
**Strategic Trigger:** Apex Capital portfolio companies receiving preferred photonic tensor allocation.

### Context
Elena maintains direct syndication bridge to Jensen Huang (94% tie strength). If we package NeoQuantum inference benchmarks alongside our enterprise security mesh, Apex will co-sponsor a joint architectural briefing.`,
    },
  ],
  'p-2': [
    {
      id: 'note-marcus-1',
      personId: 'p-2',
      title: 'Vance Aerospace Series B Strategy & Orbital Mesh Protocol',
      category: 'meeting_minutes',
      createdAt: 'Oct 3, 2026 · 14:00 PST',
      tags: ['Aerospace', 'Orbital Mesh', 'Telemetry'],
      actionItems: [
        'Provide encrypted telemetry spec sheet for Sovereign Allocators',
        'Review joint demo deployment scheduled for Paris Air Show',
      ],
      content: `## Executive Briefing Minutes
**Location:** Strategy Call (Secure Enclave)
**Attendees:** Marcus Vance (CEO, Vance Aerospace), Alexander Cross (CEO)

### Discussion Summary
- Marcus outlined expansion of Low Earth Orbit mesh constellation into sovereign communications.
- Key bottleneck: lack of warm introduction to Nordic Sovereign Allocators (€120M infrastructure mandate).
- Agreed to coordinate bilateral introduction through David Sterling before European procurement closes.`,
    },
  ],
  'p-3': [
    {
      id: 'note-sophia-1',
      personId: 'p-3',
      title: 'Nordic Sovereign Tech: €120M Mandate Scope Review',
      category: 'meeting_minutes',
      createdAt: 'Oct 1, 2026 · 09:30 CET',
      tags: ['Sovereign Mandate', 'Nordic Fund', 'Data Sovereignty'],
      actionItems: [
        'Prepare briefing document on multi-orbit secure key distribution',
        'Set up briefing with David Sterling in Stockholm',
      ],
      content: `## Executive Briefing Minutes
**Location:** Sovereign Enclave Video Conference
**Attendees:** Sophia Chen (Chief Investment Officer), Alexander Cross (CEO)

### Key Discussion Points
- Nordic Sovereign holds mandate for zero-trust enterprise and satellite data networks.
- Requires Tier 1 European compliance and sovereign encryption hardware keys.
- Open to co-anchoring institutional syndicate alongside Apex Capital.`,
    },
  ],
  'p-4': [
    {
      id: 'note-david-1',
      personId: 'p-4',
      title: 'Benchmark Growth: Enterprise Mesh Syndication Bridge',
      category: 'tactical_note',
      createdAt: 'Sept 25, 2026 · 16:00 PST',
      tags: ['Benchmark', 'Warm Bridge', 'Enterprise'],
      actionItems: ['Prepare one-page executive memorandum for Satya Nadella briefing'],
      content: `## Tactical Briefing Memo
**Warm Path Verification:** David confirmed 98% warm bridge to Microsoft Executive team (Satya Nadella).

### Proposed Action
Package Aetheris Enterprise Core distribution rights into Microsoft Azure Marketplace co-sell program.`,
    },
  ],
  'p-5': [
    {
      id: 'note-arthur-1',
      personId: 'p-5',
      title: 'Urgent Drift Recovery & Horizon Health RFP Alignment',
      category: 'deal_memo',
      createdAt: 'Sept 20, 2026 · 10:00 PST',
      tags: ['At-Risk', 'RFP', 'Drift Recovery'],
      actionItems: ['Schedule recovery breakfast meeting before RFP closing date'],
      content: `## Critical Account Drift Memo
**Current Status:** 48-day communication gap exceeds 30-day half-life decay threshold.

### Opportunity
$1.4M Enterprise Health Network procurement RFP published 12 days ago. Outreach must happen via David Sterling immediately.`,
    },
  ],
  'p-6': [
    {
      id: 'note-priya-1',
      personId: 'p-6',
      title: 'Photonic Neural Compute Architecture Briefing',
      category: 'tactical_note',
      createdAt: 'Sept 18, 2026 · 15:30 PST',
      tags: ['AI Deeptech', 'Photonics', 'Inference'],
      actionItems: ['Introduce Priya Sharma to Elena Rostova for Fund V allocation'],
      content: `## Strategic Compute Synergy
NeoQuantum AI demonstrated 10x optical matrix multiplication efficiency. Tremendous synergy with Apex Capital deep-tech fund.`,
    },
  ],
  'p-7': [
    {
      id: 'note-elliot-1',
      personId: 'p-7',
      title: 'Kinetic Core Systems Integration Partnership Scope',
      category: 'meeting_minutes',
      createdAt: 'Sept 22, 2026 · 13:00 PST',
      tags: ['Partnership', 'Integration', 'Kinetic'],
      actionItems: ['Finalize mutual NDA and API integration sandbox keys'],
      content: `## Executive Partnership Minutes
Kinetic Core agrees to integrate Aetheris relationship topologies into their Fortune 500 workflow suite.`,
    },
  ],
};

