/** Seeded, realistic demo content so every new surface is demonstrable in preview. */
import type {
  AvailabilityWindow, Circle, CompanyProfile, ConnectionChain, ConnectorReputation,
  ContextCapsule, DigitalHandshake, IntentCard, MeetingContinuity, OpenLoop,
  OrganizationRelationship, Outcome, Placement, RelationshipWeather, SystemRecord, TriggerMemory,
} from './models'

const day = (offset: number) => {
  const d = new Date(Date.UTC(2026, 8, 10))
  d.setUTCDate(d.getUTCDate() + offset)
  return d.toISOString().slice(0, 10)
}

export const seedSystems: SystemRecord[] = [
  {
    id: 'sys-golden-report', name: 'Golden Report', ownerId: 'me', category: 'Methodology',
    thesis: 'A forensic read of where revenue leaks before anyone buys more software.',
    description: 'A two-week diagnostic that reconstructs the revenue path — inbound handling, quoting, follow-up, renewal — and names the three points where money is actually lost, with evidence from the company’s own records.',
    bestFitCompanies: ['ForgeLine Systems', 'Meridian Field Services', 'Kestrel Industrial', 'Atlas Provisions'],
    bestFitRoles: ['CEO', 'Operating Partner', 'COO', 'VP Sales'],
    industries: ['Manufacturing', 'Field services', 'Industrial distribution'],
    geography: 'US — Midwest and Southeast first',
    proof: ['Found $2.1M of unquoted work at a 140-person fabricator', 'Cut quote turnaround from 9 days to 2 at a field-service operator'],
    placementGoal: 'Six diagnostics inside PE-backed operating companies this quarter.',
    targetPlacements: 6, activePlacements: 3, adoptionCount: 2, referralCount: 1,
    valueProposition: 'Evidence before spend. The report pays for itself or it does not ship.',
    evidence: ['Two completed engagements with written outcome memos', 'Reference call available from Nolan Pierce'],
    expectedFriction: 'Operators expect another dashboard. The first ten minutes must prove this is a diagnosis, not software.',
    whoBenefits: 'Operating partners answerable for revenue in companies they do not run day to day.',
    status: 'placing', visibility: 'network', createdAt: day(-180), updatedAt: day(-3),
  },
  {
    id: 'sys-digital-you', name: 'Digital You', ownerId: 'me', category: 'Software',
    thesis: 'Your judgment, tone and boundaries encoded so drafting never sounds automated.',
    description: 'A calibrated communication profile — directness, formality, brevity, warmth, prohibited phrases — used to draft outreach and follow-up that reads like the member wrote it.',
    bestFitCompanies: ['Raghavan Advisory', 'Beckett & Rowe', 'Halstead Bridge Capital'],
    bestFitRoles: ['Founder', 'Advisor', 'Partner', 'Connector'],
    industries: ['Professional services', 'Private equity', 'Advisory'],
    geography: 'Anywhere English-first correspondence dominates',
    proof: ['Advisors report follow-up time down from 40 minutes to 6 per relationship'],
    placementGoal: 'Place with ten advisors who write a high volume of considered correspondence.',
    targetPlacements: 10, activePlacements: 2, adoptionCount: 4, referralCount: 3,
    valueProposition: 'Correspondence at your standard, at the speed of your calendar.',
    evidence: ['Side-by-side drafts reviewed by three advisors', 'Prohibited-phrase enforcement log'],
    expectedFriction: 'People who write well are protective of their voice. Show the diff, not the promise.',
    whoBenefits: 'Advisors and connectors whose reputation lives in how they write.',
    status: 'active', visibility: 'network', createdAt: day(-150), updatedAt: day(-9),
  },
  {
    id: 'sys-intros', name: 'Aetheris Intros', ownerId: 'me', category: 'Product',
    thesis: 'The professional network that understands what everyone is trying to move.',
    description: 'People, systems, circles, intent and memory in one graph, so an introduction happens when it is justified for both sides — and the reasoning is visible.',
    bestFitCompanies: ['Northline Capital', 'Verdant Growth Partners', 'Anything But Typical'],
    bestFitRoles: ['Operating Partner', 'Founder', 'Connector', 'Managing Partner'],
    industries: ['Private equity', 'Professional services', 'Venture'],
    geography: 'US, with early density in Charlotte, Chicago and Indianapolis',
    proof: ['31 double-opt-in introductions with a 74% first-meeting rate in the pilot cohort'],
    placementGoal: 'Two design-partner funds and four founder-led firms.',
    targetPlacements: 6, activePlacements: 4, adoptionCount: 1, referralCount: 2,
    valueProposition: 'Fewer introductions, each one defensible.',
    evidence: ['Pilot cohort outcome log', 'Double opt-in audit trail'],
    expectedFriction: 'Everyone has been sold a network. The double opt-in and privacy scopes are the proof it is different.',
    whoBenefits: 'People whose credibility is spent every time they make an introduction.',
    status: 'placing', visibility: 'network', createdAt: day(-210), updatedAt: day(-1),
  },
  {
    id: 'sys-obsidian', name: 'Obsidian', ownerId: 'me', category: 'Framework',
    thesis: 'A build discipline for shipping serious internal systems without a platform team.',
    description: 'A working method for specification, data modelling and staged delivery that lets a small team ship operational software that survives audit and handover.',
    bestFitCompanies: ['Braxton Software Group', 'Northwind Health Systems', 'Solano Grid Works'],
    bestFitRoles: ['VP Engineering', 'CTO', 'Head of Applied AI'],
    industries: ['Software', 'Healthcare', 'Energy'],
    geography: 'US and Northern Europe',
    proof: ['Two internal platforms delivered with written handover and no rebuild in 18 months'],
    placementGoal: 'Place with three engineering leaders carrying internal-platform debt.',
    targetPlacements: 3, activePlacements: 1, adoptionCount: 1, referralCount: 0,
    valueProposition: 'A method your engineers will actually follow after you leave the room.',
    evidence: ['Handover documents from two deliveries', 'Post-mortem comparison against a rebuilt system'],
    expectedFriction: 'Engineering leaders resist methodology from outside. Lead with the handover artefacts.',
    whoBenefits: 'Engineering leaders who own systems they did not originally specify.',
    status: 'active', visibility: 'connections', createdAt: day(-120), updatedAt: day(-14),
  },
  {
    id: 'sys-clinical-throughput', name: 'Clinical Throughput Model', ownerId: 'p17', category: 'Process',
    thesis: 'Same staff, same rooms, more finished appointments.',
    description: 'A scheduling and staffing model that raises completed-visit throughput in multi-site clinics without adding headcount, developed across nine Ridgeline sites.',
    bestFitCompanies: ['Northwind Health Systems', 'Ridgeline Health Partners'],
    bestFitRoles: ['Head of Clinical Operations', 'COO', 'CTO'],
    industries: ['Healthcare'],
    geography: 'US multi-site outpatient networks',
    proof: ['Completed visits up 11% across nine sites with no added staff'],
    placementGoal: 'Share with two health systems facing the same staffing ceiling.',
    targetPlacements: 2, activePlacements: 1, adoptionCount: 0, referralCount: 0,
    valueProposition: 'Throughput gains that survive a bad staffing week.',
    evidence: ['Nine-site rollout data', 'Two clinical directors available as references'],
    expectedFriction: 'Clinical staff have absorbed too many process changes. Roll out one site at a time.',
    whoBenefits: 'Operations leaders judged on access and completed visits.',
    status: 'active', visibility: 'network', createdAt: day(-90), updatedAt: day(-6),
  },
]

export const seedPlacements: Placement[] = [
  {
    id: 'pl1', systemId: 'sys-golden-report', targetType: 'person', targetId: 'p2', targetLabel: 'Mina Park · Northline Capital',
    stage: 'Demo/Discussion', fitScore: 92, circleRelevance: 88, timingScore: 90,
    mutualValue: 'She needs comparable revenue reporting across eight operating companies; you need a portfolio-wide reference.',
    trustPath: ['You', 'Adrian Vale', 'Mina Park'], friction: 'Her team has already bought two reporting tools this year.',
    expectedOutcome: 'One diagnostic inside the weakest operating company, then a portfolio standard.',
    reasonFit: 'Golden Report answers the exact question her LP letter asks: where is revenue leaking.',
    reasonNow: 'Portfolio reviews are scheduled in five weeks and the reporting gap is already named.',
    nextStep: 'Send the two-page outcome memo from ForgeLine before Thursday’s call.',
    unknowns: ['Whether she can commission a single-company pilot without partner approval'],
    provenance: { sourceType: 'explicit', confidence: 88, evidenceIds: ['ev-forgeline-memo'], scope: 'shareable' },
    history: [
      { stage: 'Identified', when: day(-40), note: 'Named in the PE operating partner circle.' },
      { stage: 'Warm Path Found', when: day(-31), note: 'Adrian Vale confirmed he would vouch.' },
      { stage: 'Demo/Discussion', when: day(-6), note: 'Walked the diagnostic method on a 30 minute call.' },
    ],
    createdAt: day(-40), updatedAt: day(-6),
  },
  {
    id: 'pl2', systemId: 'sys-golden-report', targetType: 'person', targetId: 'p3', targetLabel: 'Nolan Pierce · ForgeLine Systems',
    stage: 'Adopted', fitScore: 95, circleRelevance: 80, timingScore: 70,
    mutualValue: 'He got the quoting fix; you got the reference and the numbers.',
    trustPath: ['You', 'Celeste Arden', 'Nolan Pierce'], friction: 'His sales team resents process reviews.',
    expectedOutcome: 'Referral into two Indiana manufacturers.',
    reasonFit: 'Quote turnaround was the leak and it was measurable inside two weeks.',
    reasonNow: 'He has budget signed for the second phase.',
    nextStep: 'Ask which two peers he would introduce, then let him choose the order.',
    unknowns: [],
    provenance: { sourceType: 'explicit', confidence: 96, evidenceIds: ['ev-forgeline-memo'], scope: 'shareable' },
    history: [
      { stage: 'Pilot', when: day(-120), note: 'Two-week diagnostic on the quoting path.' },
      { stage: 'Adopted', when: day(-84), note: 'Standing monthly review adopted by the sales leadership.' },
    ],
    createdAt: day(-140), updatedAt: day(-84),
  },
  {
    id: 'pl3', systemId: 'sys-golden-report', targetType: 'circle', targetId: 'cir-pe-revenue', targetLabel: 'PE Portfolio Revenue Systems',
    stage: 'Qualified', fitScore: 86, circleRelevance: 94, timingScore: 76,
    mutualValue: 'The circle wants a common revenue diagnosis; you want six placements without cold outreach.',
    trustPath: ['You', 'Elise Laurent'], friction: 'Circle members compare notes, so a weak first engagement is expensive.',
    expectedOutcome: 'Two diagnostics commissioned by different funds in the same quarter.',
    reasonFit: 'Every member is accountable for revenue in companies they do not operate.',
    reasonNow: 'Three members posted revenue-visibility intents in the last fortnight.',
    nextStep: 'Share the method summary in the circle before pitching any single fund.',
    unknowns: ['Whether the circle allows system sharing without moderator approval'],
    provenance: { sourceType: 'derived', confidence: 74, evidenceIds: ['ev-circle-intents'], scope: 'shareable' },
    history: [{ stage: 'Qualified', when: day(-12), note: 'Three matching intents inside the circle.' }],
    createdAt: day(-18), updatedAt: day(-12),
  },
  {
    id: 'pl4', systemId: 'sys-intros', targetType: 'person', targetId: 'p21', targetLabel: 'Elise Laurent · Verdant Growth Partners',
    stage: 'Intro Requested', fitScore: 89, circleRelevance: 82, timingScore: 84,
    mutualValue: 'She spends credibility on introductions weekly; Intros makes each one defensible.',
    trustPath: ['You', 'Darius Cole', 'Elise Laurent'], friction: 'She distrusts anything described as a network.',
    expectedOutcome: 'A design-partner fund with ten operating partners inside the graph.',
    reasonFit: 'Her firm’s value creation team lives or dies on warm access.',
    reasonNow: 'She said in August she was rebuilding how the firm tracks who knows whom.',
    nextStep: 'Ask Marcus whether Camille or her value-creation lead is the right first conversation.',
    unknowns: ['Whether the firm has an internal tool already committed'],
    provenance: { sourceType: 'explicit', confidence: 81, evidenceIds: ['ev-camille-aug'], scope: 'shareable' },
    history: [{ stage: 'Intro Requested', when: day(-4), note: 'Warm path requested through Darius Cole.' }],
    createdAt: day(-22), updatedAt: day(-4),
  },
  {
    id: 'pl5', systemId: 'sys-obsidian', targetType: 'person', targetId: 'p20', targetLabel: 'Idris Hale · Braxton Software Group',
    stage: 'Shared', fitScore: 84, circleRelevance: 70, timingScore: 66,
    mutualValue: 'He inherited three internal platforms; you get a method reference inside a software org.',
    trustPath: ['You', 'Kenji Vale', 'Idris Hale'], friction: 'He has been handed methodology before and ignored it.',
    expectedOutcome: 'One platform re-specified using the handover discipline.',
    reasonFit: 'His problem is ownership after handover, which is what the framework protects.',
    reasonNow: 'Two of his platform authors left in July.',
    nextStep: 'Send only the handover artefacts. No method overview.',
    unknowns: ['Whether he controls the roadmap or the product org does'],
    provenance: { sourceType: 'inferred', confidence: 62, evidenceIds: [], scope: 'private' },
    history: [{ stage: 'Shared', when: day(-16), note: 'Handover documents shared directly.' }],
    createdAt: day(-30), updatedAt: day(-16),
  },
  {
    id: 'pl6', systemId: 'sys-digital-you', targetType: 'person', targetId: 'p11', targetLabel: 'Anika Rao · Raghavan Advisory',
    stage: 'Pilot', fitScore: 90, circleRelevance: 64, timingScore: 72,
    mutualValue: 'She writes 30 considered follow-ups a week; you get a voice-fidelity reference from a demanding writer.',
    trustPath: ['You', 'Anika Rao'], friction: 'She will reject anything that flattens her tone.',
    expectedOutcome: 'Adoption across her whole advisory correspondence.',
    reasonFit: 'Her reputation is carried in writing and her volume is unsustainable.',
    reasonNow: 'She took on two new retainers in August.',
    nextStep: 'Review the prohibited-phrase list with her before expanding usage.',
    unknowns: ['Whether her associates will use it consistently'],
    provenance: { sourceType: 'explicit', confidence: 85, evidenceIds: ['ev-priya-pilot'], scope: 'shareable' },
    history: [{ stage: 'Pilot', when: day(-25), note: 'Two weeks of drafted follow-up, reviewed line by line.' }],
    createdAt: day(-45), updatedAt: day(-25),
  },
  {
    id: 'pl7', systemId: 'sys-clinical-throughput', targetType: 'person', targetId: 'p9', targetLabel: 'Elara Voss · Northwind Health Systems',
    stage: 'Warm Path Found', fitScore: 88, circleRelevance: 76, timingScore: 80,
    mutualValue: 'Lena needs throughput without hiring; Grace needs a second system to validate the model.',
    trustPath: ['Simone Adebayo', 'You', 'Elara Voss'], friction: 'Northwind is mid-EHR migration.',
    expectedOutcome: 'A two-site trial after the migration freeze lifts.',
    reasonFit: 'Both organisations hit the same staffing ceiling in outpatient access.',
    reasonNow: 'Lena’s access targets were reset for the coming quarter.',
    nextStep: 'Confirm the migration freeze date before proposing a trial window.',
    unknowns: ['Migration freeze end date'],
    provenance: { sourceType: 'derived', confidence: 71, evidenceIds: [], scope: 'shareable' },
    history: [{ stage: 'Warm Path Found', when: day(-8), note: 'You can introduce Grace and Lena directly.' }],
    createdAt: day(-11), updatedAt: day(-8),
  },
]

export const seedCircles: Circle[] = [
  {
    id: 'cir-ai-manufacturing', name: 'AI Operators in Manufacturing',
    purpose: 'Get applied AI into plants without another failed pilot.',
    description: 'Plant leaders, engineering heads and operators comparing what actually shipped on the floor — quoting, scheduling, quality inspection — and what quietly died in a pilot.',
    memberIds: ['p3', 'p14', 'p16', 'p22', 'me'], rolesRepresented: ['CEO', 'Head of Applied AI', 'General Counsel', 'Procurement'],
    sharedIntents: ['Quoting speed', 'Inspection automation', 'Vendor diligence that survives legal'],
    activeSystemIds: ['sys-golden-report'], openIntroCount: 3,
    opportunities: ['Two members are evaluating the same inspection vendor', 'Shared diligence checklist being drafted'],
    eventIds: ['e2'], relevanceScore: 91, ownerId: 'p3', moderatorIds: ['p3', 'p14'],
    visibility: 'network', purposeStatus: 'active',
    health: 'Healthy — 4 substantive posts and 2 introductions in the last fortnight.',
    discussion: [
      { id: 'd1', authorId: 'p14', text: 'Inspection models fail on lighting, not accuracy. Fix the fixture before the model.', when: '3 days ago' },
      { id: 'd2', authorId: 'p16', text: 'Happy to share the vendor diligence clauses that got past our board.', when: '6 days ago' },
    ],
    createdAt: day(-140),
  },
  {
    id: 'cir-pe-revenue', name: 'PE Portfolio Revenue Systems',
    purpose: 'Agree what good revenue visibility looks like across a portfolio.',
    description: 'Operating partners and value-creation leads working on comparable revenue reporting across companies they do not run day to day.',
    memberIds: ['p2', 'p8', 'p21', 'p1', 'me'], rolesRepresented: ['Operating Partner', 'Managing Director', 'Managing Partner', 'Connector'],
    sharedIntents: ['Comparable revenue reporting', 'Diagnostics before software', 'Operator bench'],
    activeSystemIds: ['sys-golden-report', 'sys-intros'], openIntroCount: 2,
    opportunities: ['Three members posted revenue-visibility intents this fortnight', 'One shared operator bench forming'],
    eventIds: ['e3'], relevanceScore: 94, ownerId: 'p21', moderatorIds: ['p21'],
    visibility: 'network', purposeStatus: 'active',
    health: 'Strong — highest intent density of any circle you belong to.',
    discussion: [
      { id: 'd3', authorId: 'p2', text: 'We stopped buying dashboards. We now require a written diagnosis first.', when: '5 days ago' },
    ],
    createdAt: day(-95),
  },
  {
    id: 'cir-series-a', name: 'Founders Raising Series A',
    purpose: 'Reach the right partner at the right fund with real timing.',
    description: 'Founders in market or about to be, trading partner-level intelligence, diligence expectations and honest process notes.',
    memberIds: ['p5', 'p18', 'p13', 'p9'], rolesRepresented: ['Founder', 'CTO', 'Brand Founder'],
    sharedIntents: ['Warm partner access', 'Diligence preparation', 'Pricing narrative'],
    activeSystemIds: [], openIntroCount: 4,
    opportunities: ['Two founders targeting the same fund could compare partner fit'],
    eventIds: [], relevanceScore: 68, ownerId: 'p5', moderatorIds: ['p5'],
    visibility: 'network', purposeStatus: 'active',
    health: 'Active but ask-heavy — more requests than offers this month.',
    discussion: [{ id: 'd4', authorId: 'p5', text: 'Partner-level intelligence beats fund-level intelligence every time.', when: '8 days ago' }],
    createdAt: day(-70),
  },
  {
    id: 'cir-indiana', name: 'Indiana Business Owners',
    purpose: 'Local owners solving succession, hiring and capacity together.',
    description: 'Owner-operators inside a two-hour drive of Indianapolis, meeting quarterly and trading practical help between meetings.',
    memberIds: ['p3', 'p12', 'p16'], rolesRepresented: ['CEO', 'President', 'General Counsel'],
    sharedIntents: ['Succession planning', 'Skilled trades hiring', 'Capacity expansion'],
    activeSystemIds: ['sys-golden-report'], openIntroCount: 1,
    opportunities: ['Two owners hiring the same trades in the same market'],
    eventIds: ['e2'], relevanceScore: 72, ownerId: 'p12', moderatorIds: ['p12'],
    visibility: 'network', purposeStatus: 'active',
    health: 'Steady — geography carries it more than shared intent.',
    discussion: [],
    createdAt: day(-160),
  },
  {
    id: 'cir-infra-buyers', name: 'Enterprise Infrastructure Buyers',
    purpose: 'Compare real infrastructure buying decisions before committing.',
    description: 'Engineering and procurement leaders comparing platform decisions, migration costs and vendor behaviour after the contract is signed.',
    memberIds: ['p20', 'p22', 'p9', 'p14'], rolesRepresented: ['VP Engineering', 'Procurement', 'CTO'],
    sharedIntents: ['Migration cost reality', 'Vendor behaviour post-signature', 'Internal platform debt'],
    activeSystemIds: ['sys-obsidian'], openIntroCount: 2,
    opportunities: ['Shared post-signature vendor scorecard being assembled'],
    eventIds: [], relevanceScore: 66, ownerId: 'p20', moderatorIds: ['p20'],
    visibility: 'network', purposeStatus: 'expiring',
    health: 'Cooling — the original migration question is largely answered. Consider reframing around platform debt.',
    discussion: [],
    createdAt: day(-200), expiresAt: day(20),
  },
  {
    id: 'cir-veteran-founders', name: 'Veteran Founders',
    purpose: 'Translate service experience into operating and capital credibility.',
    description: 'Founders with military backgrounds trading hiring, capital and operating advice with people who share the same vocabulary.',
    memberIds: ['p18', 'p12', 'p6'], rolesRepresented: ['Founder', 'President', 'Head of Talent'],
    sharedIntents: ['Capital access', 'Operator hiring', 'Government contracting'],
    activeSystemIds: [], openIntroCount: 1,
    opportunities: ['One member can open a government contracting path'],
    eventIds: [], relevanceScore: 58, ownerId: 'p18', moderatorIds: ['p18'],
    visibility: 'network', purposeStatus: 'active',
    health: 'Small and high trust — depth over volume.',
    discussion: [],
    createdAt: day(-110),
  },
]

export const seedIntents: IntentCard[] = [
  {
    id: 'int1', memberId: 'me', type: "I'M SCRLING", title: 'Placing Golden Report with PE-backed operators',
    statement: 'Looking for two operating partners who will commission a revenue diagnosis before buying more reporting software.',
    audience: 'Operating partners and value-creation leads', roleFilter: ['Investor', 'Operator'], companyFilter: [],
    industryFilter: ['Private equity', 'Manufacturing'], geographyFilter: 'US', urgency: 'high',
    startsAt: day(-14), expiresAt: day(30), visibility: 'network',
    valueOffered: 'A written diagnosis with evidence, or no invoice.', evidence: ['ForgeLine outcome memo'],
    relatedSystemId: 'sys-golden-report', status: 'active',
  },
  {
    id: 'int2', memberId: 'p2', type: 'I NEED', title: 'Comparable revenue reporting across eight companies',
    statement: 'I need one revenue read that survives comparison across eight operating companies before portfolio reviews.',
    audience: 'Operators who have standardised reporting post-acquisition', roleFilter: ['Operator', 'Specialist'], companyFilter: [],
    industryFilter: ['Private equity'], geographyFilter: 'Chicago / remote', urgency: 'high',
    startsAt: day(-20), expiresAt: day(18), visibility: 'network',
    valueOffered: 'Portfolio-wide access and a reference if it works.', evidence: ['LP letter revenue question'],
    status: 'active',
  },
  {
    id: 'int3', memberId: 'p3', type: "I'M BUYING", title: 'Quote turnaround under two days, permanently',
    statement: 'We doubled the sales team and quoting broke. I will buy the fix that survives a bad week, not a dashboard.',
    audience: 'Operators and specialists in industrial sales process', roleFilter: ['Operator', 'Specialist'], companyFilter: [],
    industryFilter: ['Manufacturing'], geographyFilter: 'Indianapolis, IN', urgency: 'medium',
    startsAt: day(-30), expiresAt: day(12), visibility: 'network',
    valueOffered: 'Reference, data access and two peer introductions.', evidence: ['Quote cycle audit'],
    status: 'active',
  },
  {
    id: 'int4', memberId: 'p11', type: 'I CNO INTRODUCE', title: 'Advisors and family-office principals in the Southeast',
    statement: 'I can introduce advisors and principals when the reason is specific and the timing is real.',
    audience: 'Founders and operators with a defensible reason to meet capital', roleFilter: ['Founder', 'Operator'], companyFilter: [],
    industryFilter: ['Professional services', 'Private equity'], geographyFilter: 'Southeast US', urgency: 'low',
    startsAt: day(-40), expiresAt: day(60), visibility: 'network',
    valueOffered: 'A warm, well-framed introduction with context on both sides.', evidence: [],
    status: 'active',
  },
  {
    id: 'int5', memberId: 'p18', type: "I'M BUILDING", title: 'Distributed grid monitoring for rural cooperatives',
    statement: 'Building monitoring hardware and software for cooperatives that cannot afford utility-grade systems.',
    audience: 'Energy operators, cooperative boards, hardware investors', roleFilter: ['Investor', 'Operator'], companyFilter: [],
    industryFilter: ['Energy'], geographyFilter: 'Western US', urgency: 'medium',
    startsAt: day(-25), expiresAt: day(40), visibility: 'network',
    valueOffered: 'Field data from four cooperatives and honest failure notes.', evidence: ['Pilot telemetry'],
    status: 'active',
  },
  {
    id: 'int6', memberId: 'p6', type: "I'M HIRING", title: 'Two staff engineers with industrial data experience',
    statement: 'Hiring engineers who have shipped against messy plant data, not clean warehouses.',
    audience: 'Engineering leaders and operators who can refer', roleFilter: ['Specialist', 'Operator'], companyFilter: [],
    industryFilter: ['Software', 'Manufacturing'], geographyFilter: 'New York / remote', urgency: 'high',
    startsAt: day(-10), expiresAt: day(25), visibility: 'network',
    valueOffered: 'Referral fee and a fast, respectful process.', evidence: [],
    status: 'active',
  },
  {
    id: 'int7', memberId: 'p17', type: 'I CNO HCRP', title: 'Clinic throughput without added headcount',
    statement: 'I can help operations leaders raise completed visits using scheduling and staffing changes we ran across nine sites.',
    audience: 'Multi-site clinical operations leaders', roleFilter: ['Executive', 'Operator'], companyFilter: [],
    industryFilter: ['Healthcare'], geographyFilter: 'US', urgency: 'low',
    startsAt: day(-35), expiresAt: day(55), visibility: 'network',
    valueOffered: 'The model, the rollout order, and what failed first.', evidence: ['Nine-site rollout data'],
    relatedSystemId: 'sys-clinical-throughput', status: 'active',
  },
  {
    id: 'int8', memberId: 'p21', type: "I'M EXPLORING", title: 'How our firm should track who knows whom',
    statement: 'Exploring how a value-creation team should record relationships without turning it into a CRM nobody updates.',
    audience: 'Firms who solved this, and people who build it', roleFilter: ['Founder', 'Operator', 'Connector'], companyFilter: [],
    industryFilter: ['Private equity'], geographyFilter: 'US', urgency: 'medium',
    startsAt: day(-18), expiresAt: day(22), visibility: 'network',
    valueOffered: 'Design partnership and candid feedback from ten partners.', evidence: [],
    status: 'active',
  },
  {
    id: 'int9', memberId: 'p8', type: "I'M INVESTING IN", title: 'Industrial software with proven floor adoption',
    statement: 'Investing in industrial software that plant staff use without being told to.',
    audience: 'Founders with live plant deployments', roleFilter: ['Founder'], companyFilter: [],
    industryFilter: ['Manufacturing', 'Software'], geographyFilter: 'North America', urgency: 'medium',
    startsAt: day(-45), expiresAt: day(35), visibility: 'network',
    valueOffered: 'Capital, operator references and patient diligence.', evidence: [],
    status: 'active',
  },
  {
    id: 'int10', memberId: 'p13', type: 'I NEED', title: 'A retail operator who has opened physical doors',
    statement: 'Needed: someone who has taken a brand from wholesale into owned retail without wrecking margin.',
    audience: 'Retail operators and executives', roleFilter: ['Executive', 'Operator'], companyFilter: [],
    industryFilter: ['Consumer', 'Retail'], geographyFilter: 'US', urgency: 'medium',
    startsAt: day(-60), expiresAt: day(-5), visibility: 'network',
    valueOffered: 'Advisory equity and brand work in exchange.', evidence: [],
    status: 'expired',
  },
]

export const seedWeather: RelationshipWeather[] = [
  { id: 'w-p3', memberId: 'p3', state: 'Cooling', why: 'Strong prior conversation, 41 days since pricing was requested.', formation: 88, momentum: 32, depth: 76, recencyDays: 41, reciprocity: 60, trust: 82, openLoops: 2, contextAccumulated: 24, updatedAt: day(-1) },
  { id: 'w-p2', memberId: 'p2', state: 'Active', why: 'Two exchanges in ten days and a live diagnostic discussion.', formation: 74, momentum: 88, depth: 62, recencyDays: 6, reciprocity: 71, trust: 78, openLoops: 1, contextAccumulated: 19, updatedAt: day(-1) },
  { id: 'w-p1', memberId: 'p1', state: 'Warm', why: 'Consistent reciprocity and he has vouched for you twice.', formation: 92, momentum: 70, depth: 84, recencyDays: 12, reciprocity: 90, trust: 94, openLoops: 0, contextAccumulated: 31, updatedAt: day(-2) },
  { id: 'w-p11', memberId: 'p11', state: 'Active', why: 'Live Digital You pilot with weekly review notes.', formation: 80, momentum: 84, depth: 70, recencyDays: 4, reciprocity: 82, trust: 86, openLoops: 1, contextAccumulated: 22, updatedAt: day(-1) },
  { id: 'w-p8', memberId: 'p8', state: 'Waiting', why: 'You asked Marcus for a path to Camille; the ball is with him.', formation: 66, momentum: 54, depth: 58, recencyDays: 9, reciprocity: 55, trust: 72, openLoops: 1, contextAccumulated: 12, updatedAt: day(-2) },
  { id: 'w-p5', memberId: 'p5', state: 'Dormant', why: 'No exchange in 96 days; his raise timeline has since moved.', formation: 58, momentum: 14, depth: 44, recencyDays: 96, reciprocity: 40, trust: 60, openLoops: 0, contextAccumulated: 9, updatedAt: day(-3) },
  { id: 'w-p20', memberId: 'p20', state: 'Reawakening', why: 'He reopened the handover thread after two engineers left.', formation: 52, momentum: 66, depth: 40, recencyDays: 8, reciprocity: 48, trust: 58, openLoops: 1, contextAccumulated: 11, updatedAt: day(-1) },
  { id: 'w-p4', memberId: 'p4', state: 'At Risk', why: 'A promised channel introduction is 61 days overdue on your side.', formation: 70, momentum: 22, depth: 55, recencyDays: 61, reciprocity: 28, trust: 64, openLoops: 2, contextAccumulated: 14, updatedAt: day(-2) },
]

export const seedLoops: OpenLoop[] = [
  { id: 'ol1', title: 'Send ForgeLine outcome memo to Mina Park', owner: 'me', memberId: 'p2', source: 'Call · 6 days ago', dueAt: day(2), status: 'open', priority: 'high', evidence: 'She asked for “the two-pager, not the deck”.', scope: 'shareable', createdAt: day(-6) },
  { id: 'ol2', title: 'Share pricing with Nolan Pierce', owner: 'me', memberId: 'p3', source: 'Message thread · 41 days ago', status: 'open', priority: 'high', evidence: 'He asked for phase-two pricing and never received it.', scope: 'shareable', createdAt: day(-41) },
  { id: 'ol3', title: 'Make the Grace → Lena clinical introduction', owner: 'me', memberId: 'p9', source: 'Both sides agreed · 8 days ago', trigger: 'After the Northwind EHR migration freeze lifts', status: 'open', priority: 'medium', evidence: 'Both sides agreed in principle; timing is the blocker.', scope: 'shareable', createdAt: day(-8) },
  { id: 'ol4', title: 'Marcus to confirm the right first contact at Verdant', owner: 'them', memberId: 'p8', source: 'Warm path request · 4 days ago', status: 'open', priority: 'high', evidence: 'He offered to check whether Camille or her lead should be first.', scope: 'shareable', createdAt: day(-4) },
  { id: 'ol5', title: 'Circle back with Maya after the portfolio review', owner: 'shared', memberId: 'p2', source: 'Call · 6 days ago', trigger: 'After the October portfolio review', status: 'open', priority: 'medium', evidence: 'She named the review as the decision point.', scope: 'shareable', createdAt: day(-6) },
  { id: 'ol6', title: 'Introduce Alison to a channel operator', owner: 'me', memberId: 'p4', source: 'Commitment made in June', status: 'open', priority: 'high', evidence: 'You offered this unprompted and it is now 61 days old.', scope: 'private', createdAt: day(-61) },
  { id: 'ol7', title: 'Reconnect with Prateek after his raise closes', owner: 'me', memberId: 'p5', source: 'Message thread · 96 days ago', trigger: 'On funding announcement', status: 'snoozed', priority: 'low', evidence: 'He asked to be left alone until the round closed.', scope: 'private', createdAt: day(-96) },
  { id: 'ol8', title: 'Send Priya the prohibited-phrase review', owner: 'me', memberId: 'p11', dueAt: day(1), source: 'Pilot review · 4 days ago', status: 'open', priority: 'medium', evidence: 'Agreed at the end of the weekly review call.', scope: 'shareable', createdAt: day(-4) },
]

export const seedTriggers: TriggerMemory[] = [
  {
    id: 'tg1', memberId: 'p20', sourceMemory: 'In March, Yusuf said he would revisit internal platform ownership “when someone leaves and we feel it”.',
    triggerCondition: 'Departure of a platform author at Braxton', matchedEvent: 'Two platform engineers left Braxton in July.',
    confidence: 84, recommendedAction: 'Send only the handover artefacts and reference his own words about feeling a departure.',
    scope: 'shareable', status: 'new', when: '2 days ago',
  },
  {
    id: 'tg2', memberId: 'p2', sourceMemory: 'Maya said comparable reporting only matters “when the LP letter asks”.',
    triggerCondition: 'Portfolio review or LP reporting cycle begins', matchedEvent: 'Northline scheduled portfolio reviews for October.',
    confidence: 91, recommendedAction: 'Move the diagnostic conversation before reviews, not after.',
    scope: 'shareable', status: 'new', when: '4 days ago',
  },
  {
    id: 'tg3', memberId: 'p24', sourceMemory: 'Julian mentioned entitlements expiring within seven months on two sites.',
    triggerCondition: 'Entitlement clock inside 90 days', matchedEvent: 'The tighter site is now inside 80 days.',
    confidence: 77, recommendedAction: 'Ask which site has the tightest clock before offering any capital path.',
    scope: 'private', status: 'new', when: '6 days ago',
  },
  {
    id: 'tg4', memberId: 'p15', sourceMemory: 'Nadia wanted to revisit retention work after the store expansion decision.',
    triggerCondition: 'Expansion decision announced', matchedEvent: 'Lumen approved eleven new locations in August.',
    confidence: 69, recommendedAction: 'Reopen the retention conversation with the expansion as the reason.',
    scope: 'shareable', status: 'new', when: '9 days ago',
  },
  {
    id: 'tg5', memberId: 'p5', sourceMemory: 'Prateek asked to be contacted once the round closed.',
    triggerCondition: 'Funding event announced', matchedEvent: 'No funding announcement detected yet.',
    confidence: 40, recommendedAction: 'Hold. Nothing has changed on his side.',
    scope: 'private', status: 'dismissed', when: '3 weeks ago',
  },
]

export const seedReputation: ConnectorReputation[] = [
  { id: 'rep-me', memberId: 'me', introsAccepted: 23, conversationsStarted: 31, partnershipsFormed: 4, outcomesCreated: 9, contextUsefulness: 4.6, typicalResponse: 'Within a day', introStyle: 'Written context first, then a short call', bestFor: ['Operators into PE', 'Founders into industrial buyers'] },
  { id: 'rep-p1', memberId: 'p1', introsAccepted: 88, conversationsStarted: 112, partnershipsFormed: 14, outcomesCreated: 27, contextUsefulness: 4.9, typicalResponse: 'Same day', introStyle: 'Vouches personally, expects you to be prepared', bestFor: ['Founders into advisors', 'Media and positioning'] },
  { id: 'rep-p11', memberId: 'p11', introsAccepted: 54, conversationsStarted: 61, partnershipsFormed: 9, outcomesCreated: 18, contextUsefulness: 4.8, typicalResponse: 'Within two days', introStyle: 'Precise framing, one ask at a time', bestFor: ['Capital relationships', 'Advisory placements'] },
  { id: 'rep-p8', memberId: 'p8', introsAccepted: 37, conversationsStarted: 44, partnershipsFormed: 6, outcomesCreated: 11, contextUsefulness: 4.4, typicalResponse: 'Within a week', introStyle: 'Checks with both sides before naming anyone', bestFor: ['Industrial software into capital'] },
]

export const seedChains: ConnectionChain[] = [
  {
    id: 'ch-p21', targetId: 'p21', state: 'in motion',
    steps: [
      { personId: 'me', name: 'You', strength: 100, trust: 100, relevance: 100, consent: 'agreed', note: 'You hold the reason for the conversation.' },
      { personId: 'p8', name: 'Darius Cole', strength: 72, trust: 78, relevance: 84, consent: 'asked', note: 'Has co-invested with Verdant twice.' },
      { personId: 'p21', name: 'Elise Laurent', strength: 20, trust: 40, relevance: 92, consent: 'not asked', note: 'Managing partner; guards her own inbox.' },
    ],
    recommendation: 'Do not ask Marcus for Camille. Ask whether Camille or her value-creation lead is the right person to involve first.',
    bestNextHop: 'Darius Cole',
  },
  {
    id: 'ch-p2', targetId: 'p2', state: 'complete',
    steps: [
      { personId: 'me', name: 'You', strength: 100, trust: 100, relevance: 100, consent: 'agreed', note: 'Diagnostic evidence in hand.' },
      { personId: 'p1', name: 'Adrian Vale', strength: 90, trust: 94, relevance: 76, consent: 'agreed', note: 'Vouched without being asked twice.' },
      { personId: 'p2', name: 'Mina Park', strength: 64, trust: 70, relevance: 94, consent: 'agreed', note: 'Already in discussion with you.' },
    ],
    recommendation: 'Chain complete. Keep Gary informed of the outcome — he spent credibility here.',
    bestNextHop: 'Direct to Mina Park',
  },
  {
    id: 'ch-p9', targetId: 'p9', state: 'mapped',
    steps: [
      { personId: 'me', name: 'You', strength: 100, trust: 100, relevance: 100, consent: 'agreed', note: 'You hold both sides of this one.' },
      { personId: 'p17', name: 'Simone Adebayo', strength: 68, trust: 74, relevance: 90, consent: 'agreed', note: 'Owns the throughput model and wants a second site.' },
      { personId: 'p9', name: 'Elara Voss', strength: 46, trust: 62, relevance: 88, consent: 'not asked', note: 'Mid-migration; timing is the only obstacle.' },
    ],
    recommendation: 'Confirm the migration freeze date with Lena before Grace makes any offer.',
    bestNextHop: 'Elara Voss — timing question only',
  },
]

export const seedCompanies: CompanyProfile[] = [
  {
    id: 'co-northline', name: 'Northline Capital', industry: 'Private equity', location: 'Chicago, IL', size: '8 operating companies',
    peopleIds: ['p2'], strongestEntry: 'Adrian Vale → Mina Park (vouched, warm, current)',
    contextualPaths: ['Adrian Vale has vouched for you twice', 'Elise Laurent co-invests with Northline'],
    previousConversations: ['30 minute diagnostic walkthrough, 6 days ago', 'Intro call in June about portfolio reporting'],
    dormantOpportunities: ['Operator bench for two underperforming companies'],
    relevantSystemIds: ['sys-golden-report', 'sys-intros'], openIntentIds: ['int2'], relatedCircleIds: ['cir-pe-revenue'],
    timeline: [
      { when: day(-6), text: 'Diagnostic method walkthrough with Mina Park.' },
      { when: day(-31), text: 'Adrian Vale confirmed he would vouch.' },
      { when: day(-95), text: 'Portfolio reporting gap first named in the PE circle.' },
    ],
  },
  {
    id: 'co-forgeline', name: 'ForgeLine Systems', industry: 'Manufacturing', location: 'Indianapolis, IN', size: '140 employees',
    peopleIds: ['p3'], strongestEntry: 'Direct — Nolan Pierce, adopted customer',
    contextualPaths: ['Celeste Arden originally connected you', 'Luc Moreau shares the Indiana circle'],
    previousConversations: ['Quoting diagnostic, completed', 'Phase two pricing request, unanswered for 41 days'],
    dormantOpportunities: ['Two peer manufacturers Scott offered to introduce'],
    relevantSystemIds: ['sys-golden-report'], openIntentIds: ['int3'], relatedCircleIds: ['cir-ai-manufacturing', 'cir-indiana'],
    timeline: [
      { when: day(-41), text: 'Pricing requested. Still open on your side.' },
      { when: day(-84), text: 'Monthly revenue review adopted by sales leadership.' },
      { when: day(-120), text: 'Two-week quoting diagnostic delivered.' },
    ],
  },
  {
    id: 'co-verdant', name: 'Verdant Growth Partners', industry: 'Private equity', location: 'Boston, MA', size: '11 partners',
    peopleIds: ['p21'], strongestEntry: 'Darius Cole → Elise Laurent (asked, awaiting reply)',
    contextualPaths: ['Marcus has co-invested twice', 'Camille posted a relationship-tracking intent'],
    previousConversations: ['No direct conversation yet'],
    dormantOpportunities: ['Design partnership for Aetheris Intros'],
    relevantSystemIds: ['sys-intros'], openIntentIds: ['int8'], relatedCircleIds: ['cir-pe-revenue'],
    timeline: [
      { when: day(-4), text: 'Warm path requested through Darius Cole.' },
      { when: day(-18), text: 'Camille posted an intent about tracking relationships.' },
    ],
  },
  {
    id: 'co-braxton', name: 'Braxton Software Group', industry: 'Software', location: 'Denver, CO', size: '600 employees',
    peopleIds: ['p20'], strongestEntry: 'Kenji Vale → Idris Hale',
    contextualPaths: ['Elliot worked with Yusuof’s platform team on an applied AI review'],
    previousConversations: ['Handover artefacts shared 16 days ago'],
    dormantOpportunities: ['Re-specification of the oldest internal platform'],
    relevantSystemIds: ['sys-obsidian'], openIntentIds: [], relatedCircleIds: ['cir-infra-buyers'],
    timeline: [
      { when: day(-16), text: 'Handover documents shared with Idris Hale.' },
      { when: day(-60), text: 'Two platform authors resigned.' },
    ],
  },
  {
    id: 'co-northwind', name: 'Northwind Health Systems', industry: 'Healthcare', location: 'Minneapolis, MN', size: '2,400 employees',
    peopleIds: ['p9'], strongestEntry: 'You → Elara Voss, with Simone Adebayo as the substance',
    contextualPaths: ['Simone Adebayo owns a validated throughput model', 'Shared infrastructure circle with Idris Hale'],
    previousConversations: ['Introductory conversation about access targets'],
    dormantOpportunities: ['Two-site throughput trial after the migration freeze'],
    relevantSystemIds: ['sys-clinical-throughput'], openIntentIds: [], relatedCircleIds: ['cir-infra-buyers', 'cir-series-a'],
    timeline: [
      { when: day(-8), text: 'Warm path found for the Grace introduction.' },
      { when: day(-50), text: 'EHR migration freeze announced.' },
    ],
  },
]

export const seedOrgRelationships: OrganizationRelationship[] = [
  { id: 'or1', companyName: 'Northline Capital', ownerId: 'p1', ownerName: 'Adrian Vale', relationshipType: 'can open door', strength: 90, scope: 'team', note: 'Has vouched for two people into Northline this year.' },
  { id: 'or2', companyName: 'Northline Capital', ownerId: 'me', ownerName: 'You', relationshipType: 'knows', strength: 64, scope: 'organization', note: 'Live diagnostic discussion with Mina Park.' },
  { id: 'or3', companyName: 'ForgeLine Systems', ownerId: 'me', ownerName: 'You', relationshipType: 'sold to', strength: 88, scope: 'organization', note: 'Golden Report adopted; pricing follow-up outstanding.' },
  { id: 'or4', companyName: 'ForgeLine Systems', ownerId: 'p4', ownerName: 'Celeste Arden', relationshipType: 'worked there', strength: 70, scope: 'team', note: 'Ran channel partnerships alongside their sales org.' },
  { id: 'or5', companyName: 'Verdant Growth Partners', ownerId: 'p8', ownerName: 'Darius Cole', relationshipType: 'can open door', strength: 78, scope: 'team', note: 'Co-invested twice; will check the right first contact.' },
  { id: 'or6', companyName: 'Braxton Software Group', ownerId: 'p14', ownerName: 'Kenji Vale', relationshipType: 'knows', strength: 66, scope: 'team', note: 'Reviewed their applied AI roadmap in 2025.' },
  { id: 'or7', companyName: 'Atlas Provisions', ownerId: 'me', ownerName: 'You', relationshipType: 'owes follow-up', strength: 40, scope: 'private', note: 'Procurement question unanswered from July.' },
]

export const seedAvailability: AvailabilityWindow[] = [
  { id: 'av1', memberId: 'me', label: 'Intro windows', day: 'Tuesday', start: '09:00', end: '11:00', timezone: 'ET', purpose: 'intro' },
  { id: 'av2', memberId: 'me', label: 'Intro windows', day: 'Thursday', start: '14:00', end: '16:00', timezone: 'ET', purpose: 'intro' },
  { id: 'av3', memberId: 'me', label: 'Demonstrations', day: 'Wednesday', start: '10:00', end: '12:00', timezone: 'ET', purpose: 'demo' },
  { id: 'av4', memberId: 'p2', label: 'Portfolio hours', day: 'Thursday', start: '14:30', end: '15:30', timezone: 'CT', purpose: 'demo' },
  { id: 'av5', memberId: 'p2', label: 'Portfolio hours', day: 'Tuesday', start: '09:30', end: '10:30', timezone: 'CT', purpose: 'intro' },
  { id: 'av6', memberId: 'p3', label: 'Plant mornings', day: 'Tuesday', start: '10:00', end: '10:45', timezone: 'ET', purpose: 'working session' },
  { id: 'av7', memberId: 'p11', label: 'Advisory review', day: 'Wednesday', start: '11:00', end: '11:45', timezone: 'ET', purpose: 'working session' },
  { id: 'av8', memberId: 'p21', label: 'Partner slots', day: 'Thursday', start: '15:00', end: '15:30', timezone: 'ET', purpose: 'intro' },
]

export const seedMeetings: MeetingContinuity[] = [
  {
    id: 'mt1', memberId: 'p2', when: 'Thursday · 14:30 CT', purpose: 'Decide whether a single-company diagnostic can start before portfolio reviews.',
    goals: ['Agree the pilot company', 'Confirm who signs', 'Set the evidence standard'],
    openLoopIds: ['ol1', 'ol5'],
    sharedContext: ['Comparable reporting across eight companies', 'ForgeLine quoting outcome', 'Adrian Vale vouched'],
    questions: ['Which company has the worst revenue visibility today?', 'Who besides you has to agree?', 'What would make this indefensible internally?'],
    desiredOutcome: 'A named pilot company and a start date before the October reviews.',
    closed: false,
  },
  {
    id: 'mt2', memberId: 'p3', when: 'Completed · 41 days ago', purpose: 'Phase two scope and pricing for the quoting work.',
    goals: ['Scope phase two', 'Agree pricing shape'], openLoopIds: ['ol2'],
    sharedContext: ['Quote turnaround cut from 9 days to 2', 'Sales leadership adopted the review'],
    questions: ['What breaks first in a bad week?'], desiredOutcome: 'Signed phase two.',
    closed: true,
    after: {
      whatChanged: 'He committed to phase two verbally, contingent on pricing.',
      decisions: ['Phase two approved in principle'],
      commitments: ['You: send pricing', 'Scott: name two peer manufacturers'],
      objections: ['Sales team fatigue with process reviews'],
      peopleMentioned: ['Luc Moreau', 'Micah Kone'],
      nextTrigger: 'Pricing sent',
      followUp: 'Pricing is 41 days overdue. Send it before anything else.',
      weather: 'Cooling',
    },
  },
]

export const seedOutcomes: Outcome[] = [
  { id: 'out1', type: 'system adoption', headline: 'ForgeLine adopted the monthly revenue review', memberId: 'p3', systemId: 'sys-golden-report', companyName: 'ForgeLine Systems', directValue: { state: 'known', note: 'Phase one engagement completed and paid.' }, influencedValue: { state: 'modeled', note: '$2.1M of previously unquoted work identified; conversion not yet confirmed.' }, evidence: 'Written outcome memo signed by the sales leadership.', confidence: 94, createdAt: day(-84) },
  { id: 'out2', type: 'meeting', headline: 'Diagnostic walkthrough with Northline Capital', memberId: 'p2', systemId: 'sys-golden-report', companyName: 'Northline Capital', directValue: { state: 'unquantified', note: 'First substantive meeting.' }, influencedValue: { state: 'unquantified', note: 'Portfolio-wide standard still open.' }, evidence: 'Calendar record and follow-up request for the two-page memo.', confidence: 88, createdAt: day(-6) },
  { id: 'out3', type: 'pilot', headline: 'Digital You pilot running inside Raghavan Advisory', memberId: 'p11', systemId: 'sys-digital-you', companyName: 'Raghavan Advisory', directValue: { state: 'known', note: 'Two-week paid pilot.' }, influencedValue: { state: 'modeled', note: 'Follow-up time reduced from 40 to 6 minutes per relationship.' }, evidence: 'Weekly review notes with line-by-line edits.', confidence: 90, createdAt: day(-25) },
  { id: 'out4', type: 'referral', headline: 'Nolan Pierce offered two peer manufacturer introductions', memberId: 'p3', systemId: 'sys-golden-report', directValue: { state: 'unquantified', note: 'Referral offered, not yet taken up.' }, influencedValue: { state: 'unquantified', note: 'Depends which peers accept.' }, evidence: 'Meeting close-out notes.', confidence: 72, createdAt: day(-84) },
  { id: 'out5', type: 'partnership', headline: 'Clinical throughput model shared between Ridgeline and Northwind', memberId: 'p17', systemId: 'sys-clinical-throughput', circleId: 'cir-infra-buyers', directValue: { state: 'unquantified', note: 'Trial pending migration freeze.' }, influencedValue: { state: 'modeled', note: '11% completed-visit lift observed at Ridgeline.' }, evidence: 'Nine-site rollout data shared with both parties.', confidence: 71, createdAt: day(-8) },
  { id: 'out6', type: 'hire', headline: 'Caleb Wynn filled one staff engineer role from a circle referral', memberId: 'p6', circleId: 'cir-ai-manufacturing', directValue: { state: 'known', note: 'One hire completed.' }, influencedValue: { state: 'unquantified', note: 'Second role still open.' }, evidence: 'Offer accepted, referred by a circle member.', confidence: 85, createdAt: day(-30) },
]

export const seedHandshakes: DigitalHandshake[] = [
  {
    id: 'hs1', aId: 'me', bId: 'p2', justified: 'Yes',
    mutualValue: 'She needs a defensible revenue read before portfolio reviews; you need a portfolio-wide reference.',
    sharedContext: ['PE Portfolio Revenue Systems circle', 'Adrian Vale vouches for both sides', 'ForgeLine outcome is directly comparable'],
    timing: 'Portfolio reviews in five weeks. This is the window.',
    potentialConflict: 'Her firm bought two reporting tools this year; a third purchase reads badly internally.',
    safeToShare: ['ForgeLine quoting outcome', 'Your placement goal for this quarter', 'Diagnostic method summary'],
    privateContextUsed: 3,
    whatAGets: 'A named pilot company and a reference that travels across the portfolio.',
    whatBGets: 'A written diagnosis she can put in front of partners without buying software.',
    whyNow: 'The reporting gap is already named and the review date is fixed.',
    confidence: 88, aApproved: true, bApproved: true, createdAt: day(-7),
  },
]

export const seedCapsules: ContextCapsule[] = [
  {
    id: 'cap1', introId: 'hs1', memberId: 'p2',
    whyMeeting: 'Northline needs one revenue read that survives comparison across eight companies. You have delivered that diagnosis once with evidence.',
    commonGround: ['Both work through operators, not software vendors', 'Adrian Vale vouches for both of you', 'Same circle: PE Portfolio Revenue Systems'],
    mutualValue: 'A defensible diagnosis for her partners; a portfolio-wide reference for you.',
    startHere: 'Open with the ForgeLine number and how it was found, not with the method.',
    helpA: ['Revenue leak diagnosis with evidence', 'Operator references in manufacturing'],
    helpB: ['Access to eight operating companies', 'A reference that carries weight with other funds'],
    currentIntents: ['Maya: comparable revenue reporting across eight companies', 'You: two operating-partner placements this quarter'],
    connectedBy: 'Adrian Vale · Anything But Typical',
    items: [
      { id: 'ci1', label: 'ForgeLine outcome memo', value: '$2.1M of unquoted work identified; quote cycle 9 days → 2 days.', shared: true, scope: 'shareable' },
      { id: 'ci2', label: 'Your placement goal', value: 'Six diagnostics inside PE-backed operating companies this quarter.', shared: true, scope: 'shareable' },
      { id: 'ci3', label: 'Circle overlap', value: 'Both active in PE Portfolio Revenue Systems.', shared: true, scope: 'public' },
      { id: 'ci4', label: 'Prior tool purchases', value: 'Northline bought two reporting tools in the last year.', shared: false, scope: 'private' },
    ],
    protected: ['Your private notes on Northline’s internal politics', 'Gary’s candid assessment of the portfolio', 'Your pricing floor'],
    createdAt: day(-7),
  },
]
