import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowRight, BarChart3, BrainCircuit, CalendarDays, Check, CheckCircle2, ChevronLeft,
  ChevronRight, CircleDot, Clock3, Command, Eye, Fingerprint, Handshake, LockKeyhole, Mail,
  Menu, MessageSquareText, Network, Plus, Search, Send, Settings, ShieldCheck, Sparkles, Target,
  UserRound, UsersRound, X, Zap, AlertTriangle, SlidersHorizontal
} from 'lucide-react'
import { defaultDigitalYou, leaks, meetings, objectives as seedObjectives, people as seedPeople } from './data'
import type { AutonomyLevel, DigitalYouProfile, Objective, Person, PrivacyScope } from './types'
import { classifyConnection, composeWarmIntro, radarLabel } from './lib/engine'

type Page = 'home' | 'intros' | 'people' | 'messages' | 'memory' | 'needs' | 'insights' | 'profile'
type MemoryNote = { id:string; personId:string; text:string; scope:PrivacyScope; createdAt:string }
type OptIn = 'pending'|'yes'|'no'
const nav:Array<{id:Page;label:string;icon:typeof Command}> = [
  {id:'home',label:'Home',icon:Command},{id:'intros',label:'Intros',icon:Handshake},
  {id:'people',label:'People',icon:UsersRound},{id:'messages',label:'Messages',icon:MessageSquareText},
  {id:'memory',label:'Memory',icon:Network},{id:'needs',label:'Needs',icon:Target},
  {id:'insights',label:'Insights',icon:BarChart3},{id:'profile',label:'Profile',icon:UserRound},
]
const legacyPage:Record<string,Page>={command:'home',network:'memory',forensics:'insights',meetings:'messages','digital-you':'profile',roi:'insights',settings:'profile'}
const scopeLabel:Record<PrivacyScope,string>={private:'Private',team:'Team',organization:'Organization',shareable:'Shareable',public:'Public'}
const scopeText:Record<PrivacyScope,string>={private:'Only you. It informs relevance but is never quoted.',team:'Visible to your trusted team.',organization:'Visible across your organization.',shareable:'Cleared for an introduction.',public:'Already public context.'}
const scopes:PrivacyScope[]=['private','team','organization','shareable','public']

function Brand(){return <div className="brand-mark"><span className="brand-monogram">AI</span><span className="brand-name">Aetheris<em>Intros</em></span></div>}
function Avatar({person,large=false}:{person:Person;large?:boolean}){return <span className={`person-avatar ${large?'large':''}`}>{person.initials}</span>}
function Button({children,kind='primary',onClick,disabled=false,className=''}:{children:React.ReactNode;kind?:'primary'|'secondary'|'quiet';onClick?:()=>void;disabled?:boolean;className?:string}){return <button className={`btn ${kind} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>}
function Label({children,signal=false}:{children:React.ReactNode;signal?:boolean}){return <span className={`eyebrow ${signal?'signal':''}`}>{children}</span>}
function Score({value}:{value:number}){return <div className="editorial-score"><strong>{value}</strong><span>/100</span></div>}

function MemoryGraph({people,onSelect,compact=false}:{people:Person[];onSelect:(p:Person)=>void;compact?:boolean}){
  const positions=[[18,25],[72,16],[84,49],[67,76],[25,78],[43,36]]
  return <div className={`memory-graph ${compact?'compact':''}`}>
    <div className="graph-rings"><i/><i/><i/></div><div className="graph-lines"/>
    <button className="graph-origin" aria-label="Your current context"><Eye size={18}/><small>YOU</small></button>
    {people.map((p,i)=>{const pos=positions[i%positions.length]??[50,50];return <button key={p.id} className={`graph-node ${i===1?'selected':''} ${p.radar==='hot_now'?'signal':''}`} style={{left:`${pos[0]}%`,top:`${pos[1]}%`}} onClick={()=>onSelect(p)}><i/><span>{p.name.split(' ')[0]}</span></button>})}
    <div className="graph-taxonomy"><span>PEOPLE</span><span>COMPANIES</span><span>NEEDS</span><span>DECISIONS</span><span>INTRODUCTIONS</span><span>CONVERSATIONS</span></div>
  </div>
}

function MatchReport({person,onOpen,onIntro}:{person:Person;onOpen:()=>void;onIntro:()=>void}){return <article className="match-report">
  <header><Avatar person={person} large/><div className="match-identity"><Label>{radarLabel[person.radar]}</Label><h3>{person.name}</h3><p>{person.title} · {person.company}</p></div><Score value={person.scoreTotal}/></header>
  <div className="match-thesis"><span>WHY THIS PERSON</span><p>{person.whyThem}</p></div>
  <div className="match-columns"><div><span>LOOKING FOR</span><p>{person.needs.slice(0,2).join(' · ')}</p></div><div><span>CAN HELP WITH</span><p>{person.offers.slice(0,2).join(' · ')}</p></div></div>
  <div className="match-reasons"><div><span>WHY YOU MATTER</span><p>{person.whyYou}</p></div><div><span>WHY NOW</span><p>{person.whyNow}</p></div></div>
  <div className="trust-path"><span>TRUST PATH</span>{person.bestPath.map((x,i)=><span key={x}><b>{x}</b>{i<person.bestPath.length-1&&<ArrowRight size={12}/>}</span>)}</div>
  <footer><Button kind="quiet" onClick={onOpen}>View reasoning</Button><Button kind="secondary" onClick={onIntro}><MessageSquareText size={15}/> Message</Button><Button onClick={onIntro}><Handshake size={15}/> Request introduction</Button></footer>
</article>}

function Home({people,select,setPage,openNeed}:{people:Person[];select:(p:Person)=>void;setPage:(p:Page)=>void;openNeed:()=>void}){
  const top=[...people].sort((a,b)=>b.scoreTotal-a.scoreTotal).slice(0,3)
  return <><header className="home-question"><Label>PEOPLE × CONTEXT × OPPORTUNITY</Label><h1>What do you need<br/><em>right now?</em></h1><button className="need-input" onClick={openNeed}><span>Describe the outcome you want to create…</span><ArrowRight size={20}/></button><p>Tell Intros the outcome. It will find the people, context and path.</p></header>
  <section className="home-grid"><div className="home-matches"><div className="section-heading"><div><Label>PEOPLE TO KNOW NOW</Label><h2>Three relationships with timing.</h2></div><button className="text-action" onClick={()=>setPage('intros')}>View all <ArrowRight size={14}/></button></div>{top.map((p,i)=><button className="person-brief" key={p.id} onClick={()=>select(p)}><span className="brief-index">0{i+1}</span><Avatar person={p}/><span className="brief-copy"><strong>{p.name}</strong><small>{p.title} · {p.company}</small><p>{p.whyNow}</p></span><Score value={p.scoreTotal}/><ChevronRight size={16}/></button>)}</div>
  <aside className="attention-panel"><Label signal>REQUIRES ATTENTION</Label><h2>Two conversations are waiting on context.</h2>{people.slice(1,3).map(p=><button key={p.id} onClick={()=>select(p)}><span className="signal-dot"/><span><strong>{p.name}</strong><small>{p.nextAction}</small></span><ArrowRight size={14}/></button>)}<div className="active-need"><span>ACTIVE NEED</span><strong>Founder & PE introductions</strong><small>5 qualified conversations · critical</small></div></aside></section>
  <section className="memory-signal"><div><Label>ACTIVE MEMORY</Label><h2>The graph changed in three places.</h2><p>One role expanded. Two warm paths gained timing. A dormant relationship now warrants attention.</p><button className="text-action" onClick={()=>setPage('memory')}>Open memory <ArrowRight size={14}/></button></div><MemoryGraph people={people} onSelect={select} compact/></section></>}

function Intros({people,select,draft}:{people:Person[];select:(p:Person)=>void;draft:(p:Person)=>void}){return <><PageHead label="CURATED MATCHES" title="People worth knowing now." copy="Not a directory. Each recommendation carries mutual value, timing and a credible path."/>
  <div className="reports-list">{[...people].sort((a,b)=>b.scoreTotal-a.scoreTotal).slice(0,4).map(p=><MatchReport key={p.id} person={p} onOpen={()=>select(p)} onIntro={()=>draft(p)}/>)}</div></>}
function PageHead({label,title,copy,action}:{label:string;title:string;copy:string;action?:React.ReactNode}){return <header className="page-title"><div><Label>{label}</Label><h1>{title}</h1><p>{copy}</p></div>{action}</header>}

function People({people,select}:{people:Person[];select:(p:Person)=>void}){
  const [q,setQ]=useState('');const [filter,setFilter]=useState('All context');const filtered=people.filter(p=>`${p.name} ${p.company} ${p.location} ${p.tags} ${p.needs} ${p.offers}`.toLowerCase().includes(q.toLowerCase()))
  return <><PageHead label="RELATIONSHIP DIRECTORY" title="People, with context." copy="Search what someone needs, offers, knows and can make possible."/>
  <div className="people-tools"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search people, needs, offers or industries"/></label><button onClick={()=>setFilter(filter==='All context'?'High match':'All context')}><SlidersHorizontal size={16}/>{filter}</button></div>
  <div className="people-grid">{filtered.map(p=><button className="member-tile" key={p.id} onClick={()=>select(p)}><div className="member-top"><Avatar person={p} large/><span className="member-score">{p.scoreTotal}</span></div><Label>{p.location}</Label><h3>{p.name}</h3><p>{p.title}<br/>{p.company}</p><div className="member-context"><span>NEEDS</span><p>{p.needs[0]}</p><span>OFFERS</span><p>{p.offers[0]}</p></div><footer><span>{radarLabel[p.radar]}</span><ArrowRight size={14}/></footer></button>)}</div></>}

function Messages({people,select}:{people:Person[];select:(p:Person)=>void}){const [active,setActive]=useState(people[2]??people[0]);const [text,setText]=useState('');if(!active)return null;return <><PageHead label="CONVERSATIONS" title="Context before contact." copy="The conversation stays central. Intelligence stays beside it."/>
  <div className="messages-layout"><aside className="thread-list"><div className="thread-search"><Search size={15}/> Conversations</div>{people.slice(0,5).map((p,i)=><button className={active.id===p.id?'active':''} key={p.id} onClick={()=>setActive(p)}><Avatar person={p}/><span><strong>{p.name}</strong><small>{i===0?'Introduction context ready':p.company}</small></span>{i<2&&<i/>}</button>)}</aside>
  <section className="conversation"><header><Avatar person={active}/><div><strong>{active.name}</strong><small>{active.title} · {active.company}</small></div><button className="icon-btn" onClick={()=>select(active)}><BrainCircuit size={17}/></button></header><div className="intro-context"><Label>INTRODUCTION CONTEXT</Label><p>{active.whyNow}</p></div><div className="messages"><div className="message incoming">The timing is useful. I’m looking closely at this problem now.<small>10:42 AM</small></div><div className="message outgoing">That is exactly why I thought a conversation could be useful. No pitch—just compare notes on the current constraints.<small>10:49 AM</small></div></div><div className="composer"><button title="Draft with context"><Sparkles size={17}/></button><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write with the relationship in mind…"/><button onClick={()=>setText('')} disabled={!text.trim()}><Send size={17}/></button></div></section>
  <aside className="conversation-intel"><Label>RELATIONSHIP CONTEXT</Label><h3>Why you’re connected</h3><p>{active.whyThem}</p><dl><div><dt>ACTIVE NEED OVERLAP</dt><dd>{active.needs[0]}</dd></div><div><dt>MUTUAL CONTEXT</dt><dd>{active.bestPath.join(' → ')}</dd></div><div><dt>LAST COMMITMENT</dt><dd>Share a concise point of view before Friday.</dd></div><div><dt>NEXT MOVE</dt><dd>{active.nextAction}</dd></div></dl></aside></div></>}

function Memory({people,select,notes}:{people:Person[];select:(p:Person)=>void;notes:MemoryNote[]}){return <><PageHead label="ACTIVE MEMORY" title="What the system remembers—and why." copy="Every signal keeps its source, confidence and privacy boundary."/>
  <div className="memory-layout"><section className="memory-stage"><MemoryGraph people={people} onSelect={select}/><div className="memory-legend"><span><i className="cobalt"/>Current context</span><span><i className="amber"/>Live signal</span><span><LockKeyhole size={12}/>Private memory</span></div></section><aside className="memory-changes"><Label signal>RECENTLY LEARNED</Label><h2>Three changes to the graph.</h2>{[
    ['Role change','Alison now leads national partnerships.','Public profile · 92%'],['Conversation signal','Scott is reviewing CRM adoption this quarter.','Meeting · 96%'],['Private note',notes[0]?.text||'No private note recorded yet.','Private · explicit'],
  ].map(([k,v,s])=><article key={k}><span>{k}</span><p>{v}</p><small>{s}</small></article>)}</aside></div></>}

function Needs({objectives,onNew}:{objectives:Objective[];onNew:()=>void}){const active=objectives[0];return <><PageHead label="CASE BRIEFS" title="Needs, clearly stated." copy="A person is not an opportunity. Start with the outcome." action={<Button onClick={onNew}><Plus size={15}/>New need</Button>}/>{active&&<article className="need-case"><header><Label signal>ACTIVE · {active.priority}</Label><span>CASE 01 / {new Date().getFullYear()}</span></header><h2>{active.title}</h2><p className="case-outcome">{active.outcome}</p><div className="case-grid"><div><span>WHO COULD HELP</span><p>{active.target}</p></div><div><span>WHY NOW</span><p>{active.whyNow}</p></div><div><span>MUTUAL VALUE</span><p>{active.valueOffer}</p></div><div><span>SUCCESS</span><p>{active.success}</p></div></div><footer><span>DIAGNOSE</span><i/><span>MAP</span><i/><span>SCORE</span><i/><span>CONNECT</span><i/><span>COMPOUND</span></footer></article>}<section className="need-archive"><div className="section-heading"><div><Label>ARCHIVE</Label><h2>Prior case files.</h2></div></div>{objectives.slice(1).map(o=><article key={o.id}><span>{o.priority}</span><strong>{o.title}</strong><p>{o.outcome}</p><ArrowRight size={14}/></article>)}{objectives.length<2&&<p className="empty-state">Completed and paused needs will appear here as an evidence archive.</p>}</section></>}

function Insights({people,select}:{people:Person[];select:(p:Person)=>void}){return <><PageHead label="RELATIONSHIP INTELLIGENCE" title="Signals worth acting on." copy="No vanity metrics. Only changes that could alter an outcome."/>
  <div className="insight-numbers"><div><span>DORMANT VALUE</span><strong>2</strong><small>high-trust relationships</small></div><div><span>PROMISING PATHS</span><strong>3</strong><small>with credible connectors</small></div><div><span>COOLING</span><strong>1</strong><small>conversation needs attention</small></div></div>
  <div className="insight-list">{leaks.map((leak,i)=>{const p=people.find(x=>x.id===leak.personId);if(!p)return null;return <button key={leak.id} onClick={()=>select(p)}><span className="insight-index">0{i+1}</span><span className="insight-main"><Label signal={leak.urgency==='high'}>{leak.type}</Label><h3>{p.name}</h3><p>{leak.businessReason}</p><small>{leak.evidence}</small></span><span className="insight-confidence"><strong>{leak.confidence}</strong><small>confidence</small></span><ArrowRight size={17}/></button>})}</div>
  <section className="evidence-line"><div><Label>90 DAY RELATIONSHIP RETURN</Label><h2>More context. Better intros. Stronger outcomes.</h2></div><div className="line-chart"><svg viewBox="0 0 600 120" preserveAspectRatio="none"><path d="M0 100 C80 95 90 75 165 80 S250 30 330 55 S450 25 600 12"/><circle cx="600" cy="12" r="5"/></svg><span>$486K influenced · 46 introductions · 24 meetings</span></div></section></>}

function Profile({profile,setProfile,autonomy,setAutonomy}:{profile:DigitalYouProfile;setProfile:(x:DigitalYouProfile)=>void;autonomy:AutonomyLevel;setAutonomy:(x:AutonomyLevel)=>void}){const sliders:[keyof DigitalYouProfile,string,string,string][]=[['directness','Directness','Soft','Direct'],['formality','Formality','Casual','Formal'],['warmth','Warmth','Reserved','Warm'],['brevity','Brevity','Detailed','Tight']];return <><PageHead label="MEMBER PROFILE" title="Joseph Toney" copy="Founder · Relationship systems strategist · Charlotte, NC"/>
  <section className="profile-hero"><div className="profile-portrait">JT</div><div><Label>CURRENT FOCUS</Label><h2>Building systems that turn relationship context into better decisions.</h2><div className="profile-facts"><div><span>LOOKING FOR</span><p>PE operating partners and founder-led design partners.</p></div><div><span>CAN HELP WITH</span><p>Revenue leak forensics, AI systems and relationship strategy.</p></div><div><span>VALUES</span><p>Evidence, mutual value, good timing and human judgment.</p></div><div><span>AVAILABILITY</span><p>Selective introductions · 3 conversations this month.</p></div></div></div></section>
  <div className="profile-settings"><section><div className="section-heading"><div><Label>DIGITAL YOU</Label><h2>Relationship mode.</h2></div><Fingerprint size={20}/></div>{sliders.map(([key,label,low,high])=><label className="slider-row" key={key}><span><b>{label}</b><em>{Number(profile[key])}</em></span><input type="range" min="0" max="100" value={Number(profile[key])} onChange={e=>setProfile({...profile,[key]:Number(e.target.value)})}/><small>{low}<i>{high}</i></small></label>)}</section><section><div className="section-heading"><div><Label>PRIVACY & AUTONOMY</Label><h2>Intelligence, permissioned.</h2></div><ShieldCheck size={20}/></div><p className="settings-copy">Private context can inform relevance without becoming shareable content.</p><div className="autonomy-levels">{['Observe','Recommend','Draft','Approve','Authorized'].map((x,i)=><button className={autonomy===i?'active':''} key={x} onClick={()=>setAutonomy(i as AutonomyLevel)}><span>{i}</span><div><strong>{x}</strong><small>{i<3?'No external action':'Explicit permission required'}</small></div>{autonomy===i&&<Check size={15}/>}</button>)}</div></section></div></>}

function PersonDrawer({person,onClose,onDraft,notes,onAdd}:{person:Person|null;onClose:()=>void;onDraft:(p:Person)=>void;notes:MemoryNote[];onAdd:(id:string,text:string,scope:PrivacyScope)=>void}){const [text,setText]=useState('');const [scope,setScope]=useState<PrivacyScope>('private');if(!person)return null;return <div className="drawer-wrap" onMouseDown={onClose}><aside className="intel-drawer" onMouseDown={e=>e.stopPropagation()}><header><button className="icon-btn" onClick={onClose}><X size={17}/></button><Label>MEMBER INTELLIGENCE</Label><Score value={person.scoreTotal}/></header><div className="drawer-person"><Avatar person={person} large/><div><h2>{person.name}</h2><p>{person.title} · {person.company}</p></div></div><div className="drawer-thesis"><Label>WHY THIS INTRO</Label><h3>{classifyConnection(person.scoreTotal)}</h3><p>{person.whyThem}</p></div>{[['WHY YOU MATTER',person.whyYou],['WHY NOW',person.whyNow],['RECOMMENDED NEXT MOVE',person.nextAction]].map(([a,b])=><section key={a}><span>{a}</span><p>{b}</p></section>)}<section><span>TRUST PATH</span><div className="drawer-path">{person.bestPath.join(' → ')}</div></section><section className="drawer-memory"><div className="section-heading"><span>ACTIVE MEMORY</span><small><LockKeyhole size={11}/>privacy scoped</small></div>{notes.filter(n=>n.personId===person.id).map(n=><article key={n.id}><b>{scopeLabel[n.scope]}</b><p>{n.text}</p><small>{n.createdAt}</small></article>)}<textarea rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Record what changed in this relationship…"/><div className="scope-picker">{scopes.map(s=><button className={scope===s?'active':''} onClick={()=>setScope(s)} key={s}>{scopeLabel[s]}</button>)}</div><small>{scopeText[scope]}</small><Button kind="secondary" disabled={!text.trim()} onClick={()=>{onAdd(person.id,text.trim(),scope);setText('')}}>Record intelligence</Button></section><footer><Button kind="quiet" onClick={onClose}>Close</Button><Button onClick={()=>onDraft(person)}>Draft approach <ArrowRight size={14}/></Button></footer></aside></div>}

function IntroModal({person,onClose}:{person:Person|null;onClose:()=>void}){const [text,setText]=useState('');const [you,setYou]=useState<OptIn>('pending');const [them,setThem]=useState<OptIn>('pending');useEffect(()=>{if(person){setText(composeWarmIntro(person));setYou('pending');setThem('pending')}},[person]);if(!person)return null;const ok=you==='yes'&&them==='yes';return <div className="modal-wrap" onMouseDown={onClose}><div className="modal editorial-modal" onMouseDown={e=>e.stopPropagation()}><header><div><Label>DOUBLE OPT-IN</Label><h2>A considered introduction.</h2><p>Both sides protect the connector’s credibility.</p></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></header><div className="intro-person"><Avatar person={person}/><span><strong>{person.name}</strong><small>{person.title} · {person.company}</small></span></div><textarea rows={8} value={text} onChange={e=>setText(e.target.value)}/>{[['You',you,setYou], [person.name,them,setThem]].map(([label,value,setter])=><div className="opt-row" key={String(label)}><span><strong>{String(label)}</strong><small>Confirm this conversation is worth making.</small></span><div><button className={value==='yes'?'active':''} onClick={()=>typeof setter==='function'&&setter('yes')}>Interested</button><button className={value==='no'?'declined':''} onClick={()=>typeof setter==='function'&&setter('no')}>Not now</button></div></div>)}<div className={`authorization ${ok?'ready':''}`}>{ok?<CheckCircle2 size={17}/>:<LockKeyhole size={17}/>}<span>{ok?'Introduction authorized. Both parties agreed.':'Waiting for both parties before anything is sent.'}</span></div><footer><Button kind="quiet" onClick={onClose}>Cancel</Button><Button disabled={!ok} onClick={()=>{navigator.clipboard?.writeText(text);onClose()}}><Send size={15}/>Copy authorized intro</Button></footer></div></div>}

const blank={goal:'',who:'',outcome:'',whyNow:'',valueOffer:'',success:''}
function NeedModal({open,onClose,onCreate}:{open:boolean;onClose:()=>void;onCreate:(o:Objective)=>void}){const [form,setForm]=useState(blank);if(!open)return null;const ready=form.goal&&form.who&&form.whyNow&&form.valueOffer;return <div className="modal-wrap light-modal-wrap" onMouseDown={onClose}><div className="modal need-modal" onMouseDown={e=>e.stopPropagation()}><header><div><Label>DIAGNOSE · 01</Label><h2>What outcome are you trying to create?</h2><p>Intros begins with the need, not a list of people.</p></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></header><div className="need-form">{([['goal','What do you need right now?','Open five serious conversations…'],['who','Who could change the outcome?','Operating partners, founders, trusted connectors…'],['outcome','What would progress look like?','A working pilot inside one portfolio company…'],['whyNow','Why now?','The timing signal that makes this relevant…'],['valueOffer','What can you offer them?','A useful perspective, access or capability…'],['success','What does success mean?','A second meeting with the right owner…']] as const).map(([key,label,placeholder],i)=><label key={key}><span>0{i+1} / {label}</span><textarea rows={i===0?2:1} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={placeholder}/></label>)}</div><footer><Button kind="quiet" onClick={onClose}>Cancel</Button><Button disabled={!ready} onClick={()=>{onCreate({id:`o${Date.now()}`,title:form.goal,outcome:form.outcome||form.goal,target:form.who,whyNow:form.whyNow,valueOffer:form.valueOffer,success:form.success||'A qualified next conversation',priority:'high'});setForm(blank);onClose()}}>Create case brief <ArrowRight size={15}/></Button></footer></div></div>}

function ContextRail({page,people,select}:{page:Page;people:Person[];select:(p:Person)=>void}){const p=people[1]??people[0];if(!p)return null;return <aside className="context-rail"><div className="context-label"><span>CONTEXT / {page.toUpperCase()}</span><CircleDot size={12}/></div><div className="context-number"><strong>{p.scoreTotal}</strong><span>strongest<br/>active match</span></div><button className="context-person" onClick={()=>select(p)}><Avatar person={p}/><span><strong>{p.name}</strong><small>{p.company}</small></span><ArrowRight size={14}/></button><div className="context-reason"><span>WHY NOW</span><p>{p.whyNow}</p></div><div className="context-signal"><span className="signal-dot"/><div><strong>Memory changed</strong><small>3 new signals this week</small></div></div><button className="ask-button"><BrainCircuit size={16}/><span>Ask Intros</span><kbd>⌘K</kbd></button></aside>}

export default function App(){
  const stored=typeof window!=='undefined'?localStorage.getItem('aetheris-intros-page'):null
  const initial=(stored&&nav.some(n=>n.id===stored)?stored:legacyPage[stored??'']??'home') as Page
  const [page,setPage]=useState<Page>(initial);const [collapsed,setCollapsed]=useState(false);const [mobileOpen,setMobileOpen]=useState(false);const [selected,setSelected]=useState<Person|null>(null);const [draft,setDraft]=useState<Person|null>(null);const [needOpen,setNeedOpen]=useState(false)
  const [profile,setProfileState]=useState<DigitalYouProfile>(()=>{try{return JSON.parse(localStorage.getItem('aetheris-intros-dy')||'')||defaultDigitalYou}catch{return defaultDigitalYou}})
  const [autonomy,setAutonomyState]=useState<AutonomyLevel>(()=>Number(localStorage.getItem('aetheris-intros-autonomy')||'2') as AutonomyLevel)
  const [objectives,setObjectives]=useState<Objective[]>(()=>{try{return JSON.parse(localStorage.getItem('aetheris-nexus-objectives')||'')||seedObjectives}catch{return seedObjectives}})
  const [notes,setNotes]=useState<MemoryNote[]>(()=>{try{return JSON.parse(localStorage.getItem('aetheris-nexus-memory')||'')||[]}catch{return []}})
  const people=seedPeople
  useEffect(()=>localStorage.setItem('aetheris-intros-page',page),[page])
  const saveProfile=(x:DigitalYouProfile)=>{setProfileState(x);localStorage.setItem('aetheris-intros-dy',JSON.stringify(x))};const saveAutonomy=(x:AutonomyLevel)=>{setAutonomyState(x);localStorage.setItem('aetheris-intros-autonomy',String(x))}
  const addNeed=(o:Objective)=>{const x=[o,...objectives];setObjectives(x);localStorage.setItem('aetheris-nexus-objectives',JSON.stringify(x));setPage('needs')};const addNote=(personId:string,text:string,scope:PrivacyScope)=>{const x=[{id:`m${Date.now()}`,personId,text,scope,createdAt:new Date().toLocaleDateString()},...notes];setNotes(x);localStorage.setItem('aetheris-nexus-memory',JSON.stringify(x))}
  const content=useMemo(()=>({home:<Home people={people} select={setSelected} setPage={setPage} openNeed={()=>setNeedOpen(true)}/>,intros:<Intros people={people} select={setSelected} draft={setDraft}/>,people:<People people={people} select={setSelected}/>,messages:<Messages people={people} select={setSelected}/>,memory:<Memory people={people} select={setSelected} notes={notes}/>,needs:<Needs objectives={objectives} onNew={()=>setNeedOpen(true)}/>,insights:<Insights people={people} select={setSelected}/>,profile:<Profile profile={profile} setProfile={saveProfile} autonomy={autonomy} setAutonomy={saveAutonomy}/>})[page],[page,people,notes,objectives,profile,autonomy])
  return <div className={`app-shell ${collapsed?'rail-collapsed':''}`}><aside className={`nav-rail ${mobileOpen?'mobile-open':''}`}><div className="rail-head"><Brand/><button className="rail-toggle" onClick={()=>setCollapsed(!collapsed)} title="Collapse navigation"><ChevronLeft size={16}/></button></div><nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={page===item.id?'active':''} title={item.label} onClick={()=>{setPage(item.id);setMobileOpen(false)}}><Icon size={18}/><span>{item.label}</span></button>})}</nav><div className="rail-foot"><span className="live-dot"/><span>Memory live</span><button onClick={()=>setPage('profile')}><span>JT</span></button></div></aside><div className="workspace"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={19}/></button><span className="topbar-title">Aetheris Intros <i>/</i> {nav.find(n=>n.id===page)?.label}</span><div><button className="icon-btn" title="New need" onClick={()=>setNeedOpen(true)}><Plus size={18}/></button><button className="icon-btn" title="Ask Intros"><BrainCircuit size={18}/></button></div></header><div className="workspace-grid"><main className="content">{content}</main><ContextRail page={page} people={people} select={setSelected}/></div></div><nav className="mobile-nav">{nav.slice(0,5).map(item=>{const Icon=item.icon;return <button key={item.id} className={page===item.id?'active':''} onClick={()=>setPage(item.id)}><Icon size={18}/><span>{item.label}</span></button>})}</nav><PersonDrawer person={selected} onClose={()=>setSelected(null)} onDraft={p=>{setSelected(null);setDraft(p)}} notes={notes} onAdd={addNote}/><IntroModal person={draft} onClose={()=>setDraft(null)}/><NeedModal open={needOpen} onClose={()=>setNeedOpen(false)} onCreate={addNeed}/></div>
}
